export enum MatchMessageType {
  CONTEXT = 'CONTEXT',
  PLAYER_ACTION = 'PLAYER_ACTION',
  OPPONENT_REACTION = 'OPPONENT_REACTION',
  RESULT = 'RESULT',
  SUBSTITUTION = 'SUBSTITUTION',
  INJURY = 'INJURY',
  YELLOW_CARD = 'YELLOW_CARD',
  RED_CARD = 'RED_CARD',
  RESTART = 'RESTART',
  LAST_PLAY = 'LAST_PLAY',
  FINAL = 'FINAL',
  INFO = 'INFO',
}
