export enum CoachProfile {
  CONSERVATIVE = 'CONSERVATIVE',
  BALANCED = 'BALANCED',
  AGGRESSIVE = 'AGGRESSIVE',
  PRAGMATIC = 'PRAGMATIC',
  CATENACCIO = 'CATENACCIO',
  REACTIVE = 'REACTIVE',
  TOTAL_FOOTBALL = 'TOTAL_FOOTBALL',
}
