export enum WorldCupCoreErrorCode {
  WC_SQUAD_UNAVAILABLE = 'WC_SQUAD_UNAVAILABLE',
  WC_TEAM_HISTORY_UNAVAILABLE = 'WC_TEAM_HISTORY_UNAVAILABLE',
  WC_SIMULATION_UNAVAILABLE = 'WC_SIMULATION_UNAVAILABLE',
  WC_SIMULATION_FETCH_FAILED = 'WC_SIMULATION_FETCH_FAILED',
  WC_PLAY_FINAL_UNAVAILABLE = 'WC_PLAY_FINAL_UNAVAILABLE',
  WC_PLAY_FINAL_FETCH_FAILED = 'WC_PLAY_FINAL_FETCH_FAILED',
}
