-- =============================================
-- POPULATE TEAM PLAYERS - PLANTILLAS REALES 2026
-- 23 jugadores por selección (basado en convocatorias recientes y proyecciones abril 2026)
-- =============================================

-- Limpiar mocks anteriores
DELETE FROM team_players;

-- Insertar jugadores reales
INSERT INTO team_players (playerId, teamId, name, position, shirtNumber, age) VALUES

-- ==================== AFC ====================

-- Australia (aus) - Captain: Mathew Ryan
('ply_aus_01', 'aus', 'Mathew Ryan', 'GK', 1, 34),
('ply_aus_02', 'aus', 'Joe Gauci', 'GK', 12, 25),
('ply_aus_03', 'aus', 'Cameron Burgess', 'DF', 4, 29),
('ply_aus_04', 'aus', 'Kye Rowles', 'DF', 5, 28),
('ply_aus_05', 'aus', 'Harry Souttar', 'DF', 19, 27),
('ply_aus_06', 'aus', 'Aziz Behich', 'DF', 16, 35),
('ply_aus_07', 'aus', 'Nathaniel Atkinson', 'DF', 3, 26),
('ply_aus_08', 'aus', 'Jackson Irvine', 'MF', 14, 32),
('ply_aus_09', 'aus', 'Aaron Mooy', 'MF', 13, 35),
('ply_aus_10', 'aus', 'Ajdin Hrustic', 'MF', 23, 29),
('ply_aus_11', 'aus', 'Craig Goodwin', 'FW', 11, 34),
('ply_aus_12', 'aus', 'Mitchell Duke', 'FW', 9, 35),
('ply_aus_13', 'aus', 'Kusini Yengi', 'FW', 20, 26),
('ply_aus_14', 'aus', 'Martin Boyle', 'FW', 7, 33),
('ply_aus_15', 'aus', 'Riley McGree', 'MF', 8, 27),
('ply_aus_16', 'aus', 'Keanu Baccus', 'MF', 22, 27),
('ply_aus_17', 'aus', 'Thomas Deng', 'DF', 2, 28),
('ply_aus_18', 'aus', 'Gethin Jones', 'DF', 6, 29),
('ply_aus_19', 'aus', 'Denis Genreau', 'MF', 17, 26),
('ply_aus_20', 'aus', 'Brandon Borrello', 'FW', 10, 31),
('ply_aus_21', 'aus', 'Jamie Maclaren', 'FW', 15, 32),
('ply_aus_22', 'aus', 'Apostolos Giannou', 'FW', 21, 36),
('ply_aus_23', 'aus', 'Lawrence Thomas', 'GK', 18, 33),

-- Iran (irn) - Captain: Mehdi Taremi
('ply_irn_01', 'irn', 'Mehdi Taremi', 'FW', 9, 33),
('ply_irn_02', 'irn', 'Alireza Beiranvand', 'GK', 1, 33),
('ply_irn_03', 'irn', 'Hossein Kanaanizadegan', 'DF', 4, 31),
('ply_irn_04', 'irn', 'Shojae Khalilzadeh', 'DF', 5, 36),
('ply_irn_05', 'irn', 'Ehsan Hajsafi', 'DF', 3, 36),
('ply_irn_06', 'irn', 'Milad Mohammadi', 'DF', 12, 29),
('ply_irn_07', 'irn', 'Sadegh Moharrami', 'DF', 2, 30),
('ply_irn_08', 'irn', 'Saeid Ezatolahi', 'MF', 6, 29),
('ply_irn_09', 'irn', 'Ahmad Noorollahi', 'MF', 8, 32),
('ply_irn_10', 'irn', 'Ali Gholizadeh', 'MF', 7, 29),
('ply_irn_11', 'irn', 'Mehdi Ghayedi', 'FW', 10, 26),
('ply_irn_12', 'irn', 'Saman Ghoddos', 'FW', 20, 32),
('ply_irn_13', 'irn', 'Karim Ansarifard', 'FW', 11, 35),
('ply_irn_14', 'irn', 'Mohammad Mohebi', 'FW', 17, 27),
('ply_irn_15', 'irn', 'Rouzbeh Cheshmi', 'MF', 15, 31),
('ply_irn_16', 'irn', 'Omid Ebrahimi', 'MF', 14, 37),
('ply_irn_17', 'irn', 'Aref Aghasi', 'DF', 13, 27),
('ply_irn_18', 'irn', 'Mohammad Amin Hazbavi', 'DF', 19, 24),
('ply_irn_19', 'irn', 'Allahyar Sayyadmanesh', 'FW', 18, 25),
('ply_irn_20', 'irn', 'Saman Fallah', 'MF', 21, 24),
('ply_irn_21', 'irn', 'Payam Niazmand', 'GK', 22, 29),
('ply_irn_22', 'irn', 'Sardar Azmoun', 'FW', 23, 31),
('ply_irn_23', 'irn', 'Alireza Jahanbakhsh', 'FW', 16, 32),

-- Iraq (irq) - Captain: Jalal Hassan
('ply_irq_01', 'irq', 'Jalal Hassan', 'GK', 1, 34),
('ply_irq_02', 'irq', 'Mohammed Hameed', 'GK', 12, 32),
('ply_irq_03', 'irq', 'Rebin Sulaka', 'DF', 4, 32),
('ply_irq_04', 'irq', 'Saad Natiq', 'DF', 5, 31),
('ply_irq_05', 'irq', 'Ahmed Yahya', 'DF', 2, 28),
('ply_irq_06', 'irq', 'Hussein Ali', 'DF', 3, 25),
('ply_irq_07', 'irq', 'Ali Adnan', 'DF', 6, 31),
('ply_irq_08', 'irq', 'Bashar Resan', 'MF', 8, 30),
('ply_irq_09', 'irq', 'Zidane Iqbal', 'MF', 10, 23),
('ply_irq_10', 'irq', 'Amjad Attwan', 'MF', 7, 28),
('ply_irq_11', 'irq', 'Aymen Hussein', 'FW', 9, 29),
('ply_irq_12', 'irq', 'Mohanad Ali', 'FW', 11, 27),
('ply_irq_13', 'irq', 'Ali Al-Hamadi', 'FW', 18, 24),
('ply_irq_14', 'irq', 'Safaa Hadi', 'MF', 14, 26),
('ply_irq_15', 'irq', 'Osama Rashid', 'MF', 15, 33),
('ply_irq_16', 'irq', 'Ibrahim Bayesh', 'FW', 19, 25),
('ply_irq_17', 'irq', 'Merchas Doski', 'DF', 20, 26),
('ply_irq_18', 'irq', 'Youssef Amyn', 'FW', 21, 22),
('ply_irq_19', 'irq', 'Mohammed Al-Mukhtar', 'DF', 13, 29),
('ply_irq_20', 'irq', 'Fahad Talib', 'GK', 22, 30),
('ply_irq_21', 'irq', 'Ahmed Al-Sarori', 'FW', 23, 27),
('ply_irq_22', 'irq', 'Ali Jasim', 'FW', 17, 23),
('ply_irq_23', 'irq', 'Sajjad Jassim', 'MF', 16, 24),

-- Japan (jpn) - Captain: Wataru Endo
('ply_jpn_01', 'jpn', 'Wataru Endo', 'MF', 6, 32),
('ply_jpn_02', 'jpn', 'Zion Suzuki', 'GK', 1, 23),
('ply_jpn_03', 'jpn', 'Takehiro Tomiyasu', 'DF', 4, 27),
('ply_jpn_04', 'jpn', 'Kou Itakura', 'DF', 3, 29),
('ply_jpn_05', 'jpn', 'Hiroki Ito', 'DF', 5, 26),
('ply_jpn_06', 'jpn', 'Yukinari Sugawara', 'DF', 2, 25),
('ply_jpn_07', 'jpn', 'Ayumu Seko', 'DF', 16, 24),
('ply_jpn_08', 'jpn', 'Hidemasa Morita', 'MF', 13, 30),
('ply_jpn_09', 'jpn', 'Ao Tanaka', 'MF', 8, 27),
('ply_jpn_10', 'jpn', 'Kaoru Mitoma', 'FW', 7, 29),
('ply_jpn_11', 'jpn', 'Takefusa Kubo', 'FW', 11, 25),
('ply_jpn_12', 'jpn', 'Ritsu Doan', 'FW', 10, 27),
('ply_jpn_13', 'jpn', 'Daichi Kamada', 'MF', 14, 29),
('ply_jpn_14', 'jpn', 'Junya Ito', 'FW', 9, 33),
('ply_jpn_15', 'jpn', 'Koki Ogawa', 'FW', 18, 28),
('ply_jpn_16', 'jpn', 'Keito Nakamura', 'FW', 17, 24),
('ply_jpn_17', 'jpn', 'Reo Hatate', 'MF', 15, 28),
('ply_jpn_18', 'jpn', 'Yuta Nakayama', 'DF', 19, 28),
('ply_jpn_19', 'jpn', 'Shuto Machino', 'FW', 20, 26),
('ply_jpn_20', 'jpn', 'Takumi Minamino', 'FW', 23, 31),
('ply_jpn_21', 'jpn', 'Kosuke Matsui', 'GK', 22, 24),
('ply_jpn_22', 'jpn', 'Hiroki Sakai', 'DF', 12, 36),
('ply_jpn_23', 'jpn', 'Yuto Nagatomo', 'DF', 21, 39),

-- Jordan (jor) - Captain: Musa Al-Taamari
('ply_jor_01', 'jor', 'Musa Al-Taamari', 'FW', 10, 29),
('ply_jor_02', 'jor', 'Yazeed Abu Laila', 'GK', 1, 30),
('ply_jor_03', 'jor', 'Abdullah Nasib', 'DF', 5, 31),
('ply_jor_04', 'jor', 'Yazan Al-Arab', 'DF', 4, 29),
('ply_jor_05', 'jor', 'Salem Al-Ajalin', 'DF', 3, 32),
('ply_jor_06', 'jor', 'Ihsan Haddad', 'DF', 2, 31),
('ply_jor_07', 'jor', 'Mohannad Khair Alla', 'DF', 6, 28),
('ply_jor_08', 'jor', 'Nizar Al-Rashdan', 'MF', 8, 26),
('ply_jor_09', 'jor', 'Mahmoud Al-Mardi', 'MF', 7, 30),
('ply_jor_10', 'jor', 'Noor Al-Rawabdeh', 'MF', 14, 28),
('ply_jor_11', 'jor', 'Yazid Jarrar', 'FW', 9, 29),
('ply_jor_12', 'jor', 'Hamza Al-Dardour', 'FW', 11, 35),
('ply_jor_13', 'jor', 'Anas Al-Awadat', 'FW', 20, 27),
('ply_jor_14', 'jor', 'Mohammad Abu Zraiq', 'FW', 17, 26),
('ply_jor_15', 'jor', 'Baha Faisal', 'FW', 21, 29),
('ply_jor_16', 'jor', 'Feras Shelbaieh', 'DF', 13, 32),
('ply_jor_17', 'jor', 'Saif Adnan', 'MF', 15, 30),
('ply_jor_18', 'jor', 'Rami Al-Hajj', 'MF', 16, 25),
('ply_jor_19', 'jor', 'Amer Shafi', 'GK', 12, 38),
('ply_jor_20', 'jor', 'Ahmad Ersan', 'FW', 18, 28),
('ply_jor_21', 'jor', 'Aref Al-Hajj', 'MF', 19, 24),
('ply_jor_22', 'jor', 'Saleh Rateb', 'MF', 23, 29),
('ply_jor_23', 'jor', 'Qusai Al-Jundi', 'GK', 22, 26),

-- Qatar (qat) - Captain: Hassan Al-Haydos
('ply_qat_01', 'qat', 'Hassan Al-Haydos', 'FW', 10, 35),
('ply_qat_02', 'qat', 'Meshaal Barsham', 'GK', 1, 27),
('ply_qat_03', 'qat', 'Pedro Miguel', 'DF', 2, 29),
('ply_qat_04', 'qat', 'Boualem Khoukhi', 'DF', 6, 36),
('ply_qat_05', 'qat', 'Tarek Salman', 'DF', 5, 28),
('ply_qat_06', 'qat', 'Homam Ahmed', 'DF', 3, 26),
('ply_qat_07', 'qat', 'Bassam Al-Rawi', 'DF', 4, 28),
('ply_qat_08', 'qat', 'Assim Madibo', 'MF', 8, 28),
('ply_qat_09', 'qat', 'Ali Asad', 'MF', 7, 33),
('ply_qat_10', 'qat', 'Akram Afif', 'FW', 11, 29),
('ply_qat_11', 'qat', 'Almoez Ali', 'FW', 9, 29),
('ply_qat_12', 'qat', 'Ismail Mohamad', 'FW', 12, 31),
('ply_qat_13', 'qat', 'Ahmed Alaaeldin', 'FW', 19, 29),
('ply_qat_14', 'qat', 'Mostafa Meshaal', 'MF', 20, 24),
('ply_qat_15', 'qat', 'Ahmed Fathy', 'MF', 15, 32),
('ply_qat_16', 'qat', 'Khaled Mohammed', 'MF', 14, 26),
('ply_qat_17', 'qat', 'Salem Al-Hajri', 'MF', 16, 30),
('ply_qat_18', 'qat', 'Jasem Gaber', 'DF', 13, 23),
('ply_qat_19', 'qat', 'Yousef Aymen', 'DF', 17, 24),
('ply_qat_20', 'qat', 'Saad Al-Sheeb', 'GK', 22, 36),
('ply_qat_21', 'qat', 'Mohammed Muntari', 'FW', 23, 31),
('ply_qat_22', 'qat', 'Abdulaziz Hatem', 'MF', 6, 34),
('ply_qat_23', 'qat', 'Khalifa Ababacar', 'GK', 21, 30),

-- Saudi Arabia (sau) - Captain: Salem Al-Dawsari
('ply_sau_01', 'sau', 'Salem Al-Dawsari', 'FW', 11, 34),
('ply_sau_02', 'sau', 'Mohammed Al-Owais', 'GK', 1, 34),
('ply_sau_03', 'sau', 'Ali Al-Bulaihi', 'DF', 5, 35),
('ply_sau_04', 'sau', 'Hassan Tambakti', 'DF', 4, 27),
('ply_sau_05', 'sau', 'Saud Abdulhamid', 'DF', 2, 26),
('ply_sau_06', 'sau', 'Yasser Al-Shahrani', 'DF', 6, 33),
('ply_sau_07', 'sau', 'Abdulelah Al-Malki', 'MF', 8, 29),
('ply_sau_08', 'sau', 'Salman Al-Faraj', 'MF', 7, 36),
('ply_sau_09', 'sau', 'Sami Al-Najei', 'MF', 10, 28),
('ply_sau_10', 'sau', 'Firas Al-Buraikan', 'FW', 9, 26),
('ply_sau_11', 'sau', 'Abdullah Al-Malki', 'DF', 3, 30),
('ply_sau_12', 'sau', 'Nasser Al-Dawsari', 'MF', 15, 27),
('ply_sau_13', 'sau', 'Ayman Yahya', 'FW', 23, 24),
('ply_sau_14', 'sau', 'Mohammed Kanno', 'MF', 14, 29),
('ply_sau_15', 'sau', 'Riyadh Sharahili', 'MF', 16, 30),
('ply_sau_16', 'sau', 'Ali Al-Hassan', 'MF', 19, 28),
('ply_sau_17', 'sau', 'Saud Al-Shehri', 'MF', 17, 32),
('ply_sau_18', 'sau', 'Hattan Bahebri', 'FW', 20, 33),
('ply_sau_19', 'sau', 'Abdulrahman Ghareeb', 'FW', 18, 28),
('ply_sau_20', 'sau', 'Ahmed Al-Kassar', 'GK', 22, 34),
('ply_sau_21', 'sau', 'Mukhtar Ali', 'MF', 21, 29),
('ply_sau_22', 'sau', 'Abdullah Madu', 'DF', 12, 32),
('ply_sau_23', 'sau', 'Fahad Al-Muwallad', 'FW', 13, 31),

-- South Korea (kor) - Captain: Son Heung-min
('ply_kor_01', 'kor', 'Son Heung-min', 'FW', 7, 33),
('ply_kor_02', 'kor', 'Kim Seung-gyu', 'GK', 1, 35),
('ply_kor_03', 'kor', 'Kim Min-jae', 'DF', 4, 29),
('ply_kor_04', 'kor', 'Jung Seung-hyun', 'DF', 5, 31),
('ply_kor_05', 'kor', 'Lee Ki-je', 'DF', 3, 34),
('ply_kor_06', 'kor', 'Cho Yu-min', 'DF', 19, 27),
('ply_kor_07', 'kor', 'Lee Jae-sung', 'MF', 10, 33),
('ply_kor_08', 'kor', 'Hwang In-beom', 'MF', 6, 29),
('ply_kor_09', 'kor', 'Paik Seung-ho', 'MF', 8, 29),
('ply_kor_10', 'kor', 'Lee Kang-in', 'MF', 18, 25),
('ply_kor_11', 'kor', 'Hwang Hee-chan', 'FW', 11, 30),
('ply_kor_12', 'kor', 'Cho Gue-sung', 'FW', 9, 28),
('ply_kor_13', 'kor', 'Jeong Woo-yeong', 'MF', 20, 26),
('ply_kor_14', 'kor', 'Kwon Hyeok-kyu', 'MF', 22, 25),
('ply_kor_15', 'kor', 'Kim Tae-hwan', 'DF', 2, 35),
('ply_kor_16', 'kor', 'Seol Young-woo', 'DF', 12, 27),
('ply_kor_17', 'kor', 'Hong Chul', 'DF', 14, 35),
('ply_kor_18', 'kor', 'Song Min-kyu', 'FW', 17, 26),
('ply_kor_19', 'kor', 'Oh Hyeon-gyu', 'FW', 21, 25),
('ply_kor_20', 'kor', 'Jo Hyeon-woo', 'GK', 23, 34),
('ply_kor_21', 'kor', 'Lee Chang-yong', 'DF', 15, 31),
('ply_kor_22', 'kor', 'Lee Myung-jae', 'DF', 13, 32),
('ply_kor_23', 'kor', 'Yang Min-hyeok', 'FW', 16, 19),

-- Uzbekistan (uzb) - Captain: Eldor Shomurodov
('ply_uzb_01', 'uzb', 'Eldor Shomurodov', 'FW', 9, 30),
('ply_uzb_02', 'uzb', 'Utkir Yusupov', 'GK', 1, 35),
('ply_uzb_03', 'uzb', 'Rustamjon Ashurmatov', 'DF', 5, 29),
('ply_uzb_04', 'uzb', 'Husniddin Alikulov', 'DF', 4, 26),
('ply_uzb_05', 'uzb', 'Farrukh Sayfiev', 'DF', 3, 33),
('ply_uzb_06', 'uzb', 'Otabek Shukurov', 'MF', 6, 29),
('ply_uzb_07', 'uzb', 'Jaloliddin Masharipov', 'FW', 10, 31),
('ply_uzb_08', 'uzb', 'Abbosbek Fayzullaev', 'MF', 8, 21),
('ply_uzb_09', 'uzb', 'Azizjon Turgunboev', 'FW', 7, 29),
('ply_uzb_10', 'uzb', 'Sherzod Nasrullaev', 'DF', 2, 28),
('ply_uzb_11', 'uzb', 'Oston Urunov', 'FW', 11, 24),
('ply_uzb_12', 'uzb', 'Bobir Abdixolikov', 'FW', 17, 27),
('ply_uzb_13', 'uzb', 'Abdumalik Abdullayev', 'MF', 14, 26),
('ply_uzb_14', 'uzb', 'Khamdamov', 'MF', 15, 28),
('ply_uzb_15', 'uzb', 'Ibrokhim Ibragimov', 'MF', 16, 27),
('ply_uzb_16', 'uzb', 'Husain Norchaev', 'FW', 19, 23),
('ply_uzb_17', 'uzb', 'Temur Khakimov', 'GK', 12, 26),
('ply_uzb_18', 'uzb', 'Sardor Sabirkhodjaev', 'MF', 20, 29),
('ply_uzb_19', 'uzb', 'Eldor Tursunov', 'DF', 13, 25),
('ply_uzb_20', 'uzb', 'Abdukodir Khusanov', 'DF', 23, 21),
('ply_uzb_21', 'uzb', 'Odiljon Hamrobekov', 'MF', 22, 28),
('ply_uzb_22', 'uzb', 'Sanjar Kodirkulov', 'MF', 21, 27),
('ply_uzb_23', 'uzb', 'Jamshid Iskanderov', 'MF', 18, 31),

-- ==================== CAF ====================

-- Algeria (alg) - Captain: Riyad Mahrez
('ply_alg_01', 'alg', 'Riyad Mahrez', 'FW', 7, 35),
('ply_alg_02', 'alg', 'Anthony Mandrea', 'GK', 1, 28),
('ply_alg_03', 'alg', 'Youcef Atal', 'DF', 20, 29),
('ply_alg_04', 'alg', 'Ramy Bensebaini', 'DF', 5, 30),
('ply_alg_05', 'alg', 'Aissa Mandi', 'DF', 4, 34),
('ply_alg_06', 'alg', 'Mohamed Amoura', 'FW', 9, 25),
('ply_alg_07', 'alg', 'Baghdad Bounedjah', 'FW', 11, 34),
('ply_alg_08', 'alg', 'Sofiane Feghouli', 'MF', 10, 36),
('ply_alg_09', 'alg', 'Ismael Bennacer', 'MF', 6, 28),
('ply_alg_10', 'alg', 'Houssem Aouar', 'MF', 8, 27),
('ply_alg_11', 'alg', 'Adam Ounas', 'FW', 17, 29),
('ply_alg_12', 'alg', 'Rayan Ait-Nouri', 'DF', 3, 24),
('ply_alg_13', 'alg', 'Zineddine Belaid', 'DF', 2, 25),
('ply_alg_14', 'alg', 'Ahmed Touba', 'DF', 21, 28),
('ply_alg_15', 'alg', 'Nabil Bentaleb', 'MF', 14, 31),
('ply_alg_16', 'alg', 'Ramiz Zerrouki', 'MF', 19, 26),
('ply_alg_17', 'alg', 'Farès Chaïbi', 'MF', 22, 24),
('ply_alg_18', 'alg', 'Said Benrahma', 'FW', 12, 30),
('ply_alg_19', 'alg', 'Islam Slimani', 'FW', 13, 37),
('ply_alg_20', 'alg', 'Moustapha Zeghba', 'GK', 23, 33),
('ply_alg_21', 'alg', 'Hicham Boudaoui', 'MF', 15, 26),
('ply_alg_22', 'alg', 'Yassine Brahimi', 'MF', 18, 36),
('ply_alg_23', 'alg', 'Raïs M''Bolhi', 'GK', 16, 39),

-- Cape Verde (cpv) - Captain: Ryan Mendes
('ply_cpv_01', 'cpv', 'Ryan Mendes', 'FW', 10, 35),
('ply_cpv_02', 'cpv', 'Vozinha', 'GK', 1, 38),
('ply_cpv_03', 'cpv', 'Stopira', 'DF', 4, 36),
('ply_cpv_04', 'cpv', 'Logan Costa', 'DF', 5, 24),
('ply_cpv_05', 'cpv', 'Jovane Cabral', 'FW', 7, 27),
('ply_cpv_06', 'cpv', 'Garry Rodrigues', 'FW', 11, 35),
('ply_cpv_07', 'cpv', 'Bebé', 'FW', 9, 35),
('ply_cpv_08', 'cpv', 'João Paulo', 'MF', 8, 33),
('ply_cpv_09', 'cpv', 'Patrick Andrade', 'MF', 6, 32),
('ply_cpv_10', 'cpv', 'Jamiro Monteiro', 'MF', 14, 32),
('ply_cpv_11', 'cpv', 'Willy Semedo', 'FW', 17, 31),
('ply_cpv_12', 'cpv', 'Fabrício', 'DF', 3, 33),
('ply_cpv_13', 'cpv', 'Diney', 'DF', 2, 30),
('ply_cpv_14', 'cpv', 'Kelvin Pires', 'DF', 15, 25),
('ply_cpv_15', 'cpv', 'Deroy Duarte', 'MF', 16, 26),
('ply_cpv_16', 'cpv', 'Cuca', 'MF', 18, 28),
('ply_cpv_17', 'cpv', 'Vukina', 'GK', 12, 35),
('ply_cpv_18', 'cpv', 'Gilson Tavares', 'FW', 19, 23),
('ply_cpv_19', 'cpv', 'Helton', 'FW', 20, 24),
('ply_cpv_20', 'cpv', 'Bryan Teixeira', 'MF', 21, 25),
('ply_cpv_21', 'cpv', 'Lisandro Semedo', 'FW', 22, 29),
('ply_cpv_22', 'cpv', 'Nuno Borges', 'MF', 23, 27),
('ply_cpv_23', 'cpv', 'Ivo Rodrigues', 'FW', 13, 29),

-- DR Congo (drc) - Captain: Chancel Mbemba
('ply_drc_01', 'drc', 'Chancel Mbemba', 'DF', 4, 31),
('ply_drc_02', 'drc', 'Lionel Mpasi', 'GK', 1, 30),
('ply_drc_03', 'drc', 'Arthur Masuaku', 'DF', 3, 31),
('ply_drc_04', 'drc', 'Edo Kayembe', 'MF', 6, 27),
('ply_drc_05', 'drc', 'Yoane Wissa', 'FW', 7, 28),
('ply_drc_06', 'drc', 'Cedric Bakambu', 'FW', 9, 34),
('ply_drc_07', 'drc', 'Silas Katompa Mvumpa', 'FW', 10, 27),
('ply_drc_08', 'drc', 'Gael Kakuta', 'MF', 8, 35),
('ply_drc_09', 'drc', 'Neeskens Kebano', 'FW', 11, 33),
('ply_drc_10', 'drc', 'Beni Makouana', 'FW', 20, 23),
('ply_drc_11', 'drc', 'Dylan Batubinsika', 'DF', 5, 29),
('ply_drc_12', 'drc', 'Merveille Bokadi', 'MF', 14, 31),
('ply_drc_13', 'drc', 'Aaron Tshibola', 'MF', 15, 30),
('ply_drc_14', 'drc', 'Jackson Muleka', 'FW', 17, 26),
('ply_drc_15', 'drc', 'Samuel Moutoussamy', 'MF', 18, 29),
('ply_drc_16', 'drc', 'Gedeon Kalulu', 'DF', 2, 27),
('ply_drc_17', 'drc', 'Meshack Elia', 'FW', 19, 26),
('ply_drc_18', 'drc', 'Derrick Tshimanga', 'DF', 22, 35),
('ply_drc_19', 'drc', 'Gradi Diangana', 'MF', 23, 27),
('ply_drc_20', 'drc', 'Matthias Phuati', 'GK', 12, 28),
('ply_drc_21', 'drc', 'Brayan Ntambwe', 'MF', 16, 25),
('ply_drc_22', 'drc', 'Fiston Mayele', 'FW', 21, 30),
('ply_drc_23', 'drc', 'Simon Banza', 'FW', 13, 29),

-- Egypt (egy) - Captain: Mohamed Salah
('ply_egy_01', 'egy', 'Mohamed Salah', 'FW', 10, 33),
('ply_egy_02', 'egy', 'Mohamed El Shenawy', 'GK', 1, 37),
('ply_egy_03', 'egy', 'Ahmed Hegazi', 'DF', 6, 35),
('ply_egy_04', 'egy', 'Ali Gabr', 'DF', 2, 37),
('ply_egy_05', 'egy', 'Mohamed Abdelmonem', 'DF', 4, 26),
('ply_egy_06', 'egy', 'Omar Kamal', 'DF', 3, 28),
('ply_egy_07', 'egy', 'Hamdallah', 'FW', 9, 35),
('ply_egy_08', 'egy', 'Emam Ashour', 'MF', 8, 27),
('ply_egy_09', 'egy', 'Hussein El Shahat', 'FW', 11, 32),
('ply_egy_10', 'egy', 'Mahmoud Hamdy', 'DF', 5, 29),
('ply_egy_11', 'egy', 'Mostafa Mohamed', 'FW', 7, 27),
('ply_egy_12', 'egy', 'Trezeguet', 'FW', 17, 31),
('ply_egy_13', 'egy', 'Zizo', 'FW', 22, 30),
('ply_egy_14', 'egy', 'Marwan Attia', 'MF', 14, 27),
('ply_egy_15', 'egy', 'Imad Ashraf', 'MF', 15, 28),
('ply_egy_16', 'egy', 'Ahmed Samy', 'DF', 12, 29),
('ply_egy_17', 'egy', 'Mohamed Sobhy', 'GK', 23, 26),
('ply_egy_18', 'egy', 'Ahmed Fatouh', 'DF', 13, 27),
('ply_egy_19', 'egy', 'Nasser Mansi', 'FW', 19, 27),
('ply_egy_20', 'egy', 'Yasser Ibrahim', 'DF', 20, 33),
('ply_egy_21', 'egy', 'Abdallah El Said', 'MF', 18, 36),
('ply_egy_22', 'egy', 'Mohamed Magdy Afsha', 'MF', 21, 30),
('ply_egy_23', 'egy', 'Mohamed Abou Gabal', 'GK', 16, 36),

-- Ghana (gha) - Captain: Thomas Partey
('ply_gha_01', 'gha', 'Thomas Partey', 'MF', 5, 32),
('ply_gha_02', 'gha', 'Lawrence Ati-Zigi', 'GK', 1, 29),
('ply_gha_03', 'gha', 'Daniel Amartey', 'DF', 4, 31),
('ply_gha_04', 'gha', 'Alexander Djiku', 'DF', 6, 31),
('ply_gha_05', 'gha', 'Gideon Mensah', 'DF', 3, 27),
('ply_gha_06', 'gha', 'Mohammed Kudus', 'MF', 20, 25),
('ply_gha_07', 'gha', 'André Ayew', 'FW', 10, 36),
('ply_gha_08', 'gha', 'Jordan Ayew', 'FW', 9, 34),
('ply_gha_09', 'gha', 'Antoine Semenyo', 'FW', 7, 26),
('ply_gha_10', 'gha', 'Kamaldeen Sulemana', 'FW', 11, 23),
('ply_gha_11', 'gha', 'Inaki Williams', 'FW', 19, 31),
('ply_gha_12', 'gha', 'Tariq Lamptey', 'DF', 2, 25),
('ply_gha_13', 'gha', 'Joseph Aidoo', 'DF', 15, 30),
('ply_gha_14', 'gha', 'Elisha Owusu', 'MF', 8, 28),
('ply_gha_15', 'gha', 'Salis Abdul Samed', 'MF', 14, 25),
('ply_gha_16', 'gha', 'Osman Bukari', 'FW', 17, 26),
('ply_gha_17', 'gha', 'Abdul Fatawu Issahaku', 'FW', 21, 21),
('ply_gha_18', 'gha', 'Joseph Paintsil', 'FW', 22, 28),
('ply_gha_19', 'gha', 'Denis Odoi', 'DF', 23, 36),
('ply_gha_20', 'gha', 'Richard Ofori', 'GK', 12, 32),
('ply_gha_21', 'gha', 'Mubarak Wakaso', 'MF', 18, 35),
('ply_gha_22', 'gha', 'Baba Rahman', 'DF', 13, 31),
('ply_gha_23', 'gha', 'Kingsley Schindler', 'DF', 16, 32),

-- Ivory Coast (civ) - Captain: Franck Kessie
('ply_civ_01', 'civ', 'Franck Kessie', 'MF', 8, 29),
('ply_civ_02', 'civ', 'Yahia Fofana', 'GK', 1, 24),
('ply_civ_03', 'civ', 'Wilfried Singo', 'DF', 5, 25),
('ply_civ_04', 'civ', 'Evan Ndicka', 'DF', 6, 25),
('ply_civ_05', 'civ', 'Odilon Kossounou', 'DF', 4, 24),
('ply_civ_06', 'civ', 'Serge Aurier', 'DF', 2, 33),
('ply_civ_07', 'civ', 'Sébastien Haller', 'FW', 9, 31),
('ply_civ_08', 'civ', 'Nicolas Pépé', 'FW', 7, 30),
('ply_civ_09', 'civ', 'Jean Michaël Seri', 'MF', 10, 33),
('ply_civ_10', 'civ', 'Ibrahim Sangaré', 'MF', 14, 28),
('ply_civ_11', 'civ', 'Max Gradel', 'FW', 11, 37),
('ply_civ_12', 'civ', 'Simon Adingra', 'FW', 17, 23),
('ply_civ_13', 'civ', 'Oumar Diakité', 'FW', 19, 22),
('ply_civ_14', 'civ', 'Lazare Amani', 'MF', 20, 27),
('ply_civ_15', 'civ', 'Christian Kouamé', 'FW', 21, 28),
('ply_civ_16', 'civ', 'Giannelli Imbula', 'MF', 22, 31),
('ply_civ_17', 'civ', 'Wilfried Zaha', 'FW', 23, 33),
('ply_civ_18', 'civ', 'Eric Bailly', 'DF', 3, 31),
('ply_civ_19', 'civ', 'Badra Ali Sangaré', 'GK', 12, 34),
('ply_civ_20', 'civ', 'Hamed Traorè', 'MF', 15, 26),
('ply_civ_21', 'civ', 'Jeremie Boga', 'FW', 18, 28),
('ply_civ_22', 'civ', 'Aboubakar Keita', 'MF', 16, 27),
('ply_civ_23', 'civ', 'Amad Diallo', 'FW', 13, 23),

-- Morocco (mar) - Captain: Achraf Hakimi
('ply_mar_01', 'mar', 'Achraf Hakimi', 'DF', 2, 27),
('ply_mar_02', 'mar', 'Yassine Bounou', 'GK', 1, 35),
('ply_mar_03', 'mar', 'Nayef Aguerd', 'DF', 5, 29),
('ply_mar_04', 'mar', 'Romain Saïss', 'DF', 6, 35),
('ply_mar_05', 'mar', 'Noussair Mazraoui', 'DF', 3, 28),
('ply_mar_06', 'mar', 'Sofyan Amrabat', 'MF', 4, 29),
('ply_mar_07', 'mar', 'Hakim Ziyech', 'FW', 7, 33),
('ply_mar_08', 'mar', 'Youssef En-Nesyri', 'FW', 9, 28),
('ply_mar_09', 'mar', 'Sofiane Boufal', 'FW', 10, 32),
('ply_mar_10', 'mar', 'Aziz Bouhaddouz', 'FW', 11, 38),
('ply_mar_11', 'mar', 'Bilal El Khannouss', 'MF', 8, 22),
('ply_mar_12', 'mar', 'Amine Adli', 'FW', 12, 25),
('ply_mar_13', 'mar', 'Ilias Chair', 'MF', 14, 27),
('ply_mar_14', 'mar', 'Abdessamad Ezzalzouli', 'FW', 17, 24),
('ply_mar_15', 'mar', 'Yahya Attiyat Allah', 'DF', 20, 29),
('ply_mar_16', 'mar', 'Munir Mohamedi', 'GK', 22, 36),
('ply_mar_17', 'mar', 'Jawad El Yamiq', 'DF', 13, 33),
('ply_mar_18', 'mar', 'Selim Amallah', 'MF', 15, 29),
('ply_mar_19', 'mar', 'Tarik Tissoudali', 'FW', 19, 32),
('ply_mar_20', 'mar', 'Zakaria Aboukhlal', 'FW', 23, 25),
('ply_mar_21', 'mar', 'Anass Zaroury', 'FW', 21, 25),
('ply_mar_22', 'mar', 'Abdelhamid Sabiri', 'MF', 16, 28),
('ply_mar_23', 'mar', 'Badr Benoun', 'DF', 18, 32),

-- Senegal (sen) - Captain: Sadio Mane
('ply_sen_01', 'sen', 'Sadio Mane', 'FW', 10, 34),
('ply_sen_02', 'sen', 'Edouard Mendy', 'GK', 1, 34),
('ply_sen_03', 'sen', 'Kalidou Koulibaly', 'DF', 4, 34),
('ply_sen_04', 'sen', 'Abdou Diallo', 'DF', 5, 30),
('ply_sen_05', 'sen', 'Ismail Jakobs', 'DF', 3, 26),
('ply_sen_06', 'sen', 'Idrissa Gueye', 'MF', 6, 36),
('ply_sen_07', 'sen', 'Cheikhou Kouyaté', 'MF', 8, 36),
('ply_sen_08', 'sen', 'Boulaye Dia', 'FW', 9, 29),
('ply_sen_09', 'sen', 'Habib Diallo', 'FW', 11, 30),
('ply_sen_10', 'sen', 'Ismaila Sarr', 'FW', 7, 28),
('ply_sen_11', 'sen', 'Krépin Diatta', 'FW', 12, 26),
('ply_sen_12', 'sen', 'Famara Diédhiou', 'FW', 14, 32),
('ply_sen_13', 'sen', 'Pape Matar Sarr', 'MF', 15, 23),
('ply_sen_14', 'sen', 'Moussa Niakhate', 'DF', 2, 29),
('ply_sen_15', 'sen', 'Formose Mendy', 'DF', 13, 25),
('ply_sen_16', 'sen', 'Seny Dieng', 'GK', 16, 30),
('ply_sen_17', 'sen', 'Mamadou Loum', 'MF', 18, 28),
('ply_sen_18', 'sen', 'Bamba Dieng', 'FW', 19, 26),
('ply_sen_19', 'sen', 'Iliman Ndiaye', 'FW', 20, 25),
('ply_sen_20', 'sen', 'Pathé Ciss', 'MF', 21, 30),
('ply_sen_21', 'sen', 'Abdallah Sima', 'FW', 22, 25),
('ply_sen_22', 'sen', 'Moustapha Name', 'MF', 23, 30),
('ply_sen_23', 'sen', 'Alfred Gomis', 'GK', 17, 31),

-- South Africa (rsa) - Captain: Percy Tau
('ply_rsa_01', 'rsa', 'Percy Tau', 'FW', 10, 31),
('ply_rsa_02', 'rsa', 'Ronwen Williams', 'GK', 1, 33),
('ply_rsa_03', 'rsa', 'Grant Kekana', 'DF', 5, 32),
('ply_rsa_04', 'rsa', 'Aubrey Modiba', 'DF', 3, 29),
('ply_rsa_05', 'rsa', 'Khuliso Mudau', 'DF', 2, 29),
('ply_rsa_06', 'rsa', 'Teboho Mokoena', 'MF', 4, 28),
('ply_rsa_07', 'rsa', 'Themba Zwane', 'FW', 8, 35),
('ply_rsa_08', 'rsa', 'Evidence Makgopa', 'FW', 9, 26),
('ply_rsa_09', 'rsa', 'Lyle Foster', 'FW', 11, 26),
('ply_rsa_10', 'rsa', 'Bongani Zungu', 'MF', 6, 32),
('ply_rsa_11', 'rsa', 'Sipho Mbule', 'MF', 12, 27),
('ply_rsa_12', 'rsa', 'Mothobi Mvala', 'MF', 13, 31),
('ply_rsa_13', 'rsa', 'Terrence Mashego', 'DF', 14, 28),
('ply_rsa_14', 'rsa', 'Nkosinathi Sibisi', 'DF', 15, 30),
('ply_rsa_15', 'rsa', 'Rushine De Reuck', 'DF', 16, 30),
('ply_rsa_16', 'rsa', 'Veli Mothwa', 'GK', 17, 33),
('ply_rsa_17', 'rsa', 'Thapelo Morena', 'DF', 18, 32),
('ply_rsa_18', 'rsa', 'Lebohang Maboe', 'MF', 19, 30),
('ply_rsa_19', 'rsa', 'Zakhele Lepasa', 'FW', 20, 28),
('ply_rsa_20', 'rsa', 'Darren Keet', 'GK', 21, 35),
('ply_rsa_21', 'rsa', 'Thabang Monare', 'MF', 22, 33),
('ply_rsa_22', 'rsa', 'Mduduzi Mdantsane', 'MF', 23, 30),
('ply_rsa_23', 'rsa', 'Sphelele Mkhulise', 'MF', 7, 28),

-- Tunisia (tun) - Captain: Youssef Msakni
('ply_tun_01', 'tun', 'Youssef Msakni', 'FW', 7, 35),
('ply_tun_02', 'tun', 'Aymen Dahmen', 'GK', 1, 29),
('ply_tun_03', 'tun', 'Montassar Talbi', 'DF', 4, 26),
('ply_tun_04', 'tun', 'Dylan Bronn', 'DF', 5, 29),
('ply_tun_05', 'tun', 'Ali Abdi', 'DF', 3, 31),
('ply_tun_06', 'tun', 'Ellyes Skhiri', 'MF', 6, 30),
('ply_tun_07', 'tun', 'Wahbi Khazri', 'FW', 10, 34),
('ply_tun_08', 'tun', 'Seifeddine Jaziri', 'FW', 9, 33),
('ply_tun_09', 'tun', 'Issam Jebali', 'FW', 11, 33),
('ply_tun_10', 'tun', 'Aïssa Laïdouni', 'MF', 8, 28),
('ply_tun_11', 'tun', 'Houssem Dagdoug', 'DF', 2, 27),
('ply_tun_12', 'tun', 'Hamza Mathlouthi', 'DF', 12, 33),
('ply_tun_13', 'tun', 'Ferjani Sassi', 'MF', 14, 32),
('ply_tun_14', 'tun', 'Anis Ben Slimane', 'MF', 15, 25),
('ply_tun_15', 'tun', 'Mouez Hassen', 'GK', 16, 31),
('ply_tun_16', 'tun', 'Haythem Jouini', 'FW', 17, 32),
('ply_tun_17', 'tun', 'Ali Youssef', 'FW', 18, 24),
('ply_tun_18', 'tun', 'Naim Sliti', 'FW', 19, 33),
('ply_tun_19', 'tun', 'Oussama Haddadi', 'DF', 20, 33),
('ply_tun_20', 'tun', 'Mohamed Ben Romdhane', 'MF', 21, 25),
('ply_tun_21', 'tun', 'Ghailene Chaalali', 'MF', 22, 31),
('ply_tun_22', 'tun', 'Bechir Ben Said', 'GK', 23, 30),
('ply_tun_23', 'tun', 'Wajdi Kechrida', 'DF', 13, 29),

-- ==================== CONCACAF ====================

-- Canada (can) - Captain: Alphonso Davies
('ply_can_01', 'can', 'Alphonso Davies', 'DF', 2, 25),
('ply_can_02', 'can', 'Dayne St. Clair', 'GK', 1, 28),
('ply_can_03', 'can', 'Kamal Miller', 'DF', 4, 28),
('ply_can_04', 'can', 'Steven Vitória', 'DF', 5, 38),
('ply_can_05', 'can', 'Richie Laryea', 'DF', 3, 30),
('ply_can_06', 'can', 'Jonathan Osorio', 'MF', 6, 32),
('ply_can_07', 'can', 'Cyle Larin', 'FW', 9, 30),
('ply_can_08', 'can', 'Jonathan David', 'FW', 10, 26),
('ply_can_09', 'can', 'Tajon Buchanan', 'FW', 7, 26),
('ply_can_10', 'can', 'Ike Ugbo', 'FW', 11, 27),
('ply_can_11', 'can', 'Liam Millar', 'FW', 8, 25),
('ply_can_12', 'can', 'Junior Hoilett', 'FW', 12, 35),
('ply_can_13', 'can', 'Atiba Hutchinson', 'MF', 13, 43),
('ply_can_14', 'can', 'Mark-Anthony Kaye', 'MF', 14, 30),
('ply_can_15', 'can', 'Samuel Piette', 'MF', 15, 31),
('ply_can_16', 'can', 'Alistair Johnston', 'DF', 16, 26),
('ply_can_17', 'can', 'Derek Cornelius', 'DF', 17, 27),
('ply_can_18', 'can', 'Jacob Shaffelburg', 'FW', 18, 26),
('ply_can_19', 'can', 'Ismaël Koné', 'MF', 19, 23),
('ply_can_20', 'can', 'Milan Borjan', 'GK', 20, 37),
('ply_can_21', 'can', 'Joel Waterman', 'DF', 21, 29),
('ply_can_22', 'can', 'Theo Bair', 'FW', 22, 26),
('ply_can_23', 'can', 'Thomas Hasal', 'GK', 23, 26),

-- Curacao (cuw) - Captain: Leandro Bacuna
('ply_cuw_01', 'cuw', 'Leandro Bacuna', 'MF', 6, 33),
('ply_cuw_02', 'cuw', 'Eloy Room', 'GK', 1, 35),
('ply_cuw_03', 'cuw', 'Shurandy Sambo', 'DF', 2, 23),
('ply_cuw_04', 'cuw', 'Nathaniel Chalop', 'DF', 3, 24),
('ply_cuw_05', 'cuw', 'Jurien Gaari', 'DF', 4, 32),
('ply_cuw_06', 'cuw', 'Kenji Gorre', 'FW', 7, 30),
('ply_cuw_07', 'cuw', 'Juninho Bacuna', 'MF', 8, 28),
('ply_cuw_08', 'cuw', 'Brandley Kuipers', 'DF', 5, 25),
('ply_cuw_09', 'cuw', 'Rangelo Janga', 'FW', 9, 32),
('ply_cuw_10', 'cuw', 'Gino van Kessel', 'FW', 10, 32),
('ply_cuw_11', 'cuw', 'Kevin Felida', 'MF', 11, 25),
('ply_cuw_12', 'cuw', 'Godfried Roemeratoe', 'MF', 12, 25),
('ply_cuw_13', 'cuw', 'Jarchinio Antonia', 'FW', 13, 33),
('ply_cuw_14', 'cuw', 'Tyrick Bodak', 'GK', 14, 23),
('ply_cuw_15', 'cuw', 'Sherel Floranus', 'DF', 15, 27),
('ply_cuw_16', 'cuw', 'Jeremy Antonisse', 'FW', 16, 23),
('ply_cuw_17', 'cuw', 'Richonell Margaret', 'FW', 17, 24),
('ply_cuw_18', 'cuw', 'Mitchell Dijks', 'DF', 18, 32),
('ply_cuw_19', 'cuw', 'Anthony van den Hurk', 'FW', 19, 33),
('ply_cuw_20', 'cuw', 'Darryl Lachman', 'DF', 20, 35),
('ply_cuw_21', 'cuw', 'Vurnon Anita', 'MF', 21, 36),
('ply_cuw_22', 'cuw', 'Gevaro Nepomuceno', 'FW', 22, 32),
('ply_cuw_23', 'cuw', 'Elias Nascimiento', 'GK', 23, 24),

-- Haiti (hai) - Captain: Duckens Nazon
('ply_hai_01', 'hai', 'Duckens Nazon', 'FW', 9, 31),
('ply_hai_02', 'hai', 'Johny Placide', 'GK', 1, 37),
('ply_hai_03', 'hai', 'Alex Christian', 'DF', 4, 32),
('ply_hai_04', 'hai', 'Ricardo Adé', 'DF', 5, 34),
('ply_hai_05', 'hai', 'Carlens Arcus', 'DF', 2, 31),
('ply_hai_06', 'hai', 'Derrick Etienne', 'FW', 7, 29),
('ply_hai_07', 'hai', 'Frantzdy Pierrot', 'FW', 10, 30),
('ply_hai_08', 'hai', 'Wilde-Donald Guerrier', 'FW', 11, 35),
('ply_hai_09', 'hai', 'Mikaël Cantave', 'MF', 8, 28),
('ply_hai_10', 'hai', 'Kevin Lafrance', 'FW', 12, 35),
('ply_hai_11', 'hai', 'Steeven Saba', 'MF', 6, 28),
('ply_hai_12', 'hai', 'Dany Jean', 'FW', 13, 23),
('ply_hai_13', 'hai', 'Jems Geffrard', 'DF', 3, 30),
('ply_hai_14', 'hai', 'Garvens Bélizaire', 'DF', 14, 29),
('ply_hai_15', 'hai', 'Ronaldo Damus', 'FW', 15, 25),
('ply_hai_16', 'hai', 'Jayro Jean', 'GK', 16, 26),
('ply_hai_17', 'hai', 'Christopher Attys', 'MF', 17, 24),
('ply_hai_18', 'hai', 'Carnejy Antoine', 'FW', 18, 30),
('ply_hai_19', 'hai', 'Danley Jean Jacques', 'MF', 19, 25),
('ply_hai_20', 'hai', 'Gregori', 'DF', 20, 28),
('ply_hai_21', 'hai', 'Fabrice Picault', 'FW', 21, 34),
('ply_hai_22', 'hai', 'Shanyder Borgelin', 'FW', 22, 24),
('ply_hai_23', 'hai', 'Luis Josué', 'GK', 23, 27),

-- Mexico (mex) - Captain: Edson Alvarez
('ply_mex_01', 'mex', 'Edson Alvarez', 'MF', 4, 28),
('ply_mex_02', 'mex', 'Guillermo Ochoa', 'GK', 13, 40),
('ply_mex_03', 'mex', 'Jorge Sanchez', 'DF', 2, 27),
('ply_mex_04', 'mex', 'Cesar Montes', 'DF', 3, 28),
('ply_mex_05', 'mex', 'Johan Vasquez', 'DF', 5, 27),
('ply_mex_06', 'mex', 'Gerardo Arteaga', 'DF', 6, 27),
('ply_mex_07', 'mex', 'Hirving Lozano', 'FW', 11, 30),
('ply_mex_08', 'mex', 'Santiago Gimenez', 'FW', 9, 25),
('ply_mex_09', 'mex', 'Raul Jimenez', 'FW', 7, 35),
('ply_mex_10', 'mex', 'Luis Chavez', 'MF', 8, 29),
('ply_mex_11', 'mex', 'Orbelin Pineda', 'MF', 10, 28),
('ply_mex_12', 'mex', 'Uriel Antuna', 'FW', 14, 27),
('ply_mex_13', 'mex', 'Henry Martin', 'FW', 20, 32),
('ply_mex_14', 'mex', 'Luis Romo', 'MF', 15, 30),
('ply_mex_15', 'mex', 'Kevin Alvarez', 'DF', 16, 26),
('ply_mex_16', 'mex', 'Israel Reyes', 'DF', 19, 25),
('ply_mex_17', 'mex', 'Erick Sanchez', 'MF', 17, 25),
('ply_mex_18', 'mex', 'Julian Quinones', 'FW', 18, 27),
('ply_mex_19', 'mex', 'Jorge Rodriguez', 'MF', 21, 28),
('ply_mex_20', 'mex', 'Luis Malagon', 'GK', 23, 28),
('ply_mex_21', 'mex', 'Jesus Gallardo', 'DF', 22, 31),
('ply_mex_22', 'mex', 'Roberto Alvarado', 'MF', 12, 27),
('ply_mex_23', 'mex', 'Alan Pulido', 'FW', 19, 35),  -- corregido número

-- Panama (pan) - Captain: Anibal Godoy
('ply_pan_01', 'pan', 'Anibal Godoy', 'MF', 6, 35),
('ply_pan_02', 'pan', 'Orlando Mosquera', 'GK', 1, 30),
('ply_pan_03', 'pan', 'Michael Murillo', 'DF', 4, 30),
('ply_pan_04', 'pan', 'Fidel Escobar', 'DF', 5, 30),
('ply_pan_05', 'pan', 'Andrés Andrade', 'DF', 3, 26),
('ply_pan_06', 'pan', 'José Luis Rodríguez', 'FW', 7, 28),
('ply_pan_07', 'pan', 'Ismael Díaz', 'FW', 8, 28),
('ply_pan_08', 'pan', 'Cecilio Waterman', 'FW', 9, 34),
('ply_pan_09', 'pan', 'Eduardo Guerrero', 'FW', 10, 25),
('ply_pan_10', 'pan', 'Adalberto Carrasquilla', 'MF', 11, 27),
('ply_pan_11', 'pan', 'Ernesto Walker', 'MF', 14, 27),
('ply_pan_12', 'pan', 'Alberto Quintero', 'FW', 12, 37),
('ply_pan_13', 'pan', 'Harold Cummings', 'DF', 13, 32),
('ply_pan_14', 'pan', 'Roderick Miller', 'DF', 15, 31),
('ply_pan_15', 'pan', 'Luis Mejía', 'GK', 16, 34),
('ply_pan_16', 'pan', 'Jovani Welch', 'MF', 17, 23),
('ply_pan_17', 'pan', 'Fredy Góndola', 'FW', 18, 30),
('ply_pan_18', 'pan', 'César Yanis', 'MF', 19, 31),
('ply_pan_19', 'pan', 'Omar Browne', 'FW', 20, 29),
('ply_pan_20', 'pan', 'José Fajardo', 'FW', 21, 31),
('ply_pan_21', 'pan', 'Iván Anderson', 'DF', 22, 27),
('ply_pan_22', 'pan', 'Abdiel Ayarza', 'MF', 23, 32),
('ply_pan_23', 'pan', 'Gilberto Hernández', 'DF', 2, 28),

-- United States (usa) - Captain: Christian Pulisic
('ply_usa_01', 'usa', 'Christian Pulisic', 'FW', 10, 27),
('ply_usa_02', 'usa', 'Matt Turner', 'GK', 1, 31),
('ply_usa_03', 'usa', 'Sergiño Dest', 'DF', 2, 25),
('ply_usa_04', 'usa', 'Antonee Robinson', 'DF', 3, 28),
('ply_usa_05', 'usa', 'Cameron Carter-Vickers', 'DF', 4, 27),
('ply_usa_06', 'usa', 'Tyler Adams', 'MF', 6, 27),
('ply_usa_07', 'usa', 'Weston McKennie', 'MF', 8, 27),
('ply_usa_08', 'usa', 'Yunus Musah', 'MF', 7, 22),
('ply_usa_09', 'usa', 'Ricardo Pepi', 'FW', 9, 23),
('ply_usa_10', 'usa', 'Timothy Weah', 'FW', 11, 26),
('ply_usa_11', 'usa', 'Gio Reyna', 'MF', 5, 22),
('ply_usa_12', 'usa', 'Brenden Aaronson', 'MF', 12, 25),
('ply_usa_13', 'usa', 'Folarin Balogun', 'FW', 13, 25),
('ply_usa_14', 'usa', 'Haji Wright', 'FW', 14, 27),
('ply_usa_15', 'usa', 'Miles Robinson', 'DF', 15, 29),
('ply_usa_16', 'usa', 'Chris Richards', 'DF', 16, 26),
('ply_usa_17', 'usa', 'Luca de la Torre', 'MF', 17, 27),
('ply_usa_18', 'usa', 'Jordan Pefok', 'FW', 18, 29),
('ply_usa_19', 'usa', 'Ethan Horvath', 'GK', 19, 30),
('ply_usa_20', 'usa', 'Joe Scally', 'DF', 20, 23),
('ply_usa_21', 'usa', 'Auston Trusty', 'DF', 21, 27),
('ply_usa_22', 'usa', 'Malik Tillman', 'MF', 22, 23),
('ply_usa_23', 'usa', 'Sean Johnson', 'GK', 23, 36),

-- ==================== CONMEBOL ====================

-- Argentina (arg) - Captain: Lionel Messi
('ply_arg_01', 'arg', 'Lionel Messi', 'FW', 10, 38),
('ply_arg_02', 'arg', 'Emiliano Martínez', 'GK', 23, 33),
('ply_arg_03', 'arg', 'Cristian Romero', 'DF', 13, 27),
('ply_arg_04', 'arg', 'Lisandro Martínez', 'DF', 6, 28),
('ply_arg_05', 'arg', 'Nicolás Otamendi', 'DF', 19, 38),
('ply_arg_06', 'arg', 'Nahuel Molina', 'DF', 4, 27),
('ply_arg_07', 'arg', 'Nicolás Tagliafico', 'DF', 3, 33),
('ply_arg_08', 'arg', 'Alexis Mac Allister', 'MF', 5, 26),
('ply_arg_09', 'arg', 'Enzo Fernández', 'MF', 8, 25),
('ply_arg_10', 'arg', 'Rodrigo De Paul', 'MF', 7, 31),
('ply_arg_11', 'arg', 'Julián Álvarez', 'FW', 9, 26),
('ply_arg_12', 'arg', 'Lautaro Martínez', 'FW', 11, 28),
('ply_arg_13', 'arg', 'Giuliano Simeone', 'FW', 22, 22),
('ply_arg_14', 'arg', 'Giovani Lo Celso', 'MF', 20, 29),
('ply_arg_15', 'arg', 'Paulo Dybala', 'FW', 21, 32),
('ply_arg_16', 'arg', 'Marcos Acuña', 'DF', 2, 33),
('ply_arg_17', 'arg', 'Santiago Beltrán', 'GK', 41, 21),
('ply_arg_18', 'arg', 'Leandro Paredes', 'MF', 14, 32),
('ply_arg_19', 'arg', 'Exequiel Palacios', 'MF', 15, 27),
('ply_arg_20', 'arg', 'Valentín Barco', 'DF', 16, 22),
('ply_arg_21', 'arg', 'Gonzalo Montiel', 'DF', 17, 28),
('ply_arg_22', 'arg', 'Thiago Almada', 'MF', 18, 24),
('ply_arg_23', 'arg', 'Nico Paz', 'MF', 19, 21),

-- Brazil (bra) - Captain: Marquinhos
('ply_bra_01', 'bra', 'Marquinhos', 'DF', 4, 31),
('ply_bra_02', 'bra', 'Alisson', 'GK', 1, 33),
('ply_bra_03', 'bra', 'Ederson', 'GK', 23, 32),
('ply_bra_04', 'bra', 'Danilo', 'DF', 2, 34),
('ply_bra_05', 'bra', 'Gabriel Magalhães', 'DF', 3, 28),
('ply_bra_06', 'bra', 'Thiago Silva', 'DF', 6, 41),
('ply_bra_07', 'bra', 'Casemiro', 'MF', 5, 34),
('ply_bra_08', 'bra', 'Bruno Guimarães', 'MF', 8, 27),
('ply_bra_09', 'bra', 'Lucas Paquetá', 'MF', 7, 28),
('ply_bra_10', 'bra', 'Vinícius Júnior', 'FW', 10, 25),
('ply_bra_11', 'bra', 'Rodrygo', 'FW', 11, 25),
('ply_bra_12', 'bra', 'Raphinha', 'FW', 9, 29),
('ply_bra_13', 'bra', 'Endrick', 'FW', 9, 19),
('ply_bra_14', 'bra', 'Rafael Leão', 'FW', 17, 26),
('ply_bra_15', 'bra', 'Antony', 'FW', 19, 26),
('ply_bra_16', 'bra', 'Wesley', 'DF', 12, 21),
('ply_bra_17', 'bra', 'João Gomes', 'MF', 15, 24),
('ply_bra_18', 'bra', 'Sávio', 'FW', 20, 21),
('ply_bra_19', 'bra', 'Bremer', 'DF', 14, 28),
('ply_bra_20', 'bra', 'Bento', 'GK', 21, 26),
('ply_bra_21', 'bra', 'Matheus Cunha', 'FW', 18, 27),
('ply_bra_22', 'bra', 'Estevão', 'FW', 22, 18),
('ply_bra_23', 'bra', 'Andrey Santos', 'MF', 16, 22),

-- Colombia (col) - Captain: James Rodriguez
('ply_col_01', 'col', 'James Rodriguez', 'MF', 10, 34),
('ply_col_02', 'col', 'Camilo Vargas', 'GK', 1, 36),
('ply_col_03', 'col', 'Davinson Sánchez', 'DF', 13, 29),
('ply_col_04', 'col', 'Jhon Lucumí', 'DF', 3, 30),
('ply_col_05', 'col', 'Daniel Muñoz', 'DF', 2, 29),
('ply_col_06', 'col', 'Johan Mojica', 'DF', 4, 33),
('ply_col_07', 'col', 'Luis Díaz', 'FW', 7, 29),
('ply_col_08', 'col', 'Jhon Durán', 'FW', 9, 22),
('ply_col_09', 'col', 'Rafael Borré', 'FW', 11, 30),
('ply_col_10', 'col', 'Richard Ríos', 'MF', 6, 25),
('ply_col_11', 'col', 'Mateus Uribe', 'MF', 8, 34),
('ply_col_12', 'col', 'Jefferson Lerma', 'MF', 5, 31),
('ply_col_13', 'col', 'Jorge Carrascal', 'MF', 14, 27),
('ply_col_14', 'col', 'Luis Sinisterra', 'FW', 12, 26),
('ply_col_15', 'col', 'Jhon Arias', 'FW', 15, 27),
('ply_col_16', 'col', 'Santiago Arias', 'DF', 16, 33),
('ply_col_17', 'col', 'Wilker Faríñez', 'GK', 17, 27),
('ply_col_18', 'col', 'Carlos Cuesta', 'DF', 18, 27),
('ply_col_19', 'col', 'Kevin Castaño', 'MF', 19, 24),
('ply_col_20', 'col', 'Duván Zapata', 'FW', 20, 35),
('ply_col_21', 'col', 'Miguel Borja', 'FW', 21, 32),
('ply_col_22', 'col', 'Yerry Mina', 'DF', 22, 31),
('ply_col_23', 'col', 'Mateo Cassierra', 'FW', 23, 28),

-- Ecuador (ecu) - Captain: Enner Valencia
('ply_ecu_01', 'ecu', 'Enner Valencia', 'FW', 13, 36),
('ply_ecu_02', 'ecu', 'Hernán Galíndez', 'GK', 1, 38),
('ply_ecu_03', 'ecu', 'Piero Hincapié', 'DF', 3, 24),
('ply_ecu_04', 'ecu', 'Félix Torres', 'DF', 4, 29),
('ply_ecu_05', 'ecu', 'William Pacho', 'DF', 6, 24),
('ply_ecu_06', 'ecu', 'Ángelo Preciado', 'DF', 2, 28),
('ply_ecu_07', 'ecu', 'Kendry Páez', 'MF', 8, 18),
('ply_ecu_08', 'ecu', 'Moisés Caicedo', 'MF', 5, 24),
('ply_ecu_09', 'ecu', 'Alan Franco', 'MF', 10, 26),
('ply_ecu_10', 'ecu', 'Jordy Caicedo', 'FW', 9, 28),
('ply_ecu_11', 'ecu', 'Leonardo Campana', 'FW', 11, 25),
('ply_ecu_12', 'ecu', 'Kevin Rodríguez', 'FW', 7, 26),
('ply_ecu_13', 'ecu', 'Jackson Porozo', 'DF', 14, 24),
('ply_ecu_14', 'ecu', 'Alexander Domínguez', 'GK', 12, 39),
('ply_ecu_15', 'ecu', 'Jhegson Méndez', 'MF', 15, 28),
('ply_ecu_16', 'ecu', 'Nilson Angulo', 'FW', 16, 23),
('ply_ecu_17', 'ecu', 'Joel Ordóñez', 'DF', 17, 23),
('ply_ecu_18', 'ecu', 'Oscar Estupiñán', 'FW', 18, 28),
('ply_ecu_19', 'ecu', 'Jeremy Sarmiento', 'MF', 19, 23),
('ply_ecu_20', 'ecu', 'Sebastián Méndez', 'MF', 20, 28),
('ply_ecu_21', 'ecu', 'Pedro Ortiz', 'GK', 21, 34),
('ply_ecu_22', 'ecu', 'Byron Castillo', 'DF', 22, 27),
('ply_ecu_23', 'ecu', 'Willian Pacho', 'DF', 23, 24),

-- Paraguay (par) - Captain: Gustavo Gomez
('ply_par_01', 'par', 'Gustavo Gomez', 'DF', 5, 33),
('ply_par_02', 'par', 'Carlos Coronel', 'GK', 1, 29),
('ply_par_03', 'par', 'Junior Alonso', 'DF', 3, 32),
('ply_par_04', 'par', 'Omar Alderete', 'DF', 4, 28),
('ply_par_05', 'par', 'Fabian Balbuena', 'DF', 2, 35),
('ply_par_06', 'par', 'Miguel Almirón', 'FW', 10, 31),
('ply_par_07', 'par', 'Julio Enciso', 'FW', 7, 22),
('ply_par_08', 'par', 'Jesús Medina', 'FW', 8, 31),
('ply_par_09', 'par', 'Antonio Sanabria', 'FW', 9, 30),
('ply_par_10', 'par', 'Andrés Cubas', 'MF', 6, 29),
('ply_par_11', 'par', 'Mathías Villasanti', 'MF', 11, 28),
('ply_par_12', 'par', 'Alejandro Romero Gamarra', 'MF', 14, 32),
('ply_par_13', 'par', 'Robert Rojas', 'DF', 13, 29),
('ply_par_14', 'par', 'Santiago Arzamendia', 'DF', 12, 27),
('ply_par_15', 'par', 'Richard Ortiz', 'MF', 15, 36),
('ply_par_16', 'par', 'Derlis González', 'FW', 16, 32),
('ply_par_17', 'par', 'Gabriel Ávalos', 'FW', 17, 33),
('ply_par_18', 'par', 'Ángel Romero', 'FW', 18, 33),
('ply_par_19', 'par', 'Diego Gómez', 'MF', 19, 22),
('ply_par_20', 'par', 'Alfredo Aguilar', 'GK', 20, 37),
('ply_par_21', 'par', 'Matías Espinoza', 'DF', 21, 29),
('ply_par_22', 'par', 'Hernán Pérez', 'MF', 22, 36),
('ply_par_23', 'par', 'Braian Samudio', 'FW', 23, 29),

-- Uruguay (uru) - Captain: Federico Valverde
('ply_uru_01', 'uru', 'Federico Valverde', 'MF', 15, 27),
('ply_uru_02', 'uru', 'Sergio Rochet', 'GK', 1, 32),
('ply_uru_03', 'uru', 'Ronald Araújo', 'DF', 4, 26),
('ply_uru_04', 'uru', 'José María Giménez', 'DF', 3, 31),
('ply_uru_05', 'uru', 'Mathías Olivera', 'DF', 5, 28),
('ply_uru_06', 'uru', 'Darwin Núñez', 'FW', 9, 26),
('ply_uru_07', 'uru', 'Luis Suárez', 'FW', 10, 39),
('ply_uru_08', 'uru', 'Giorgian de Arrascaeta', 'FW', 11, 31),
('ply_uru_09', 'uru', 'Nicolás de la Cruz', 'MF', 7, 28),
('ply_uru_10', 'uru', 'Matías Vecino', 'MF', 8, 34),
('ply_uru_11', 'uru', 'Rodrigo Bentancur', 'MF', 6, 28),
('ply_uru_12', 'uru', 'Facundo Pellistri', 'FW', 14, 24),
('ply_uru_13', 'uru', 'Darwin Machís', 'FW', 12, 32),
('ply_uru_14', 'uru', 'Maximiliano Araújo', 'FW', 17, 25),
('ply_uru_15', 'uru', 'Sebastián Coates', 'DF', 2, 35),
('ply_uru_16', 'uru', 'Guillermo Varela', 'DF', 13, 32),
('ply_uru_17', 'uru', 'Nahitan Nández', 'MF', 16, 29),
('ply_uru_18', 'uru', 'Agustín Canobbio', 'FW', 18, 26),
('ply_uru_19', 'uru', 'Santiago Mele', 'GK', 19, 27),
('ply_uru_20', 'uru', 'Lucas Torreira', 'MF', 20, 29),
('ply_uru_21', 'uru', 'Facundo Torres', 'FW', 21, 25),
('ply_uru_22', 'uru', 'Joaquín Piquerez', 'DF', 22, 27),
('ply_uru_23', 'uru', 'Franco Israel', 'GK', 23, 25),

-- ==================== OFC ====================

-- New Zealand (nzl) - Captain: Chris Wood
('ply_nzl_01', 'nzl', 'Chris Wood', 'FW', 9, 34),
('ply_nzl_02', 'nzl', 'Stefan Marinovic', 'GK', 1, 34),
('ply_nzl_03', 'nzl', 'Winston Reid', 'DF', 5, 37),
('ply_nzl_04', 'nzl', 'Tommy Smith', 'DF', 4, 35),
('ply_nzl_05', 'nzl', 'Michael Boxall', 'DF', 6, 36),
('ply_nzl_06', 'nzl', 'Kosta Barbarouses', 'FW', 7, 35),
('ply_nzl_07', 'nzl', 'Matthew Garbett', 'MF', 8, 23),
('ply_nzl_08', 'nzl', 'Liberato Cacace', 'DF', 3, 25),
('ply_nzl_09', 'nzl', 'Elijah Just', 'MF', 10, 24),
('ply_nzl_10', 'nzl', 'Callum McCowatt', 'FW', 11, 26),
('ply_nzl_11', 'nzl', 'Ben Waine', 'FW', 12, 24),
('ply_nzl_12', 'nzl', 'Sarpreet Singh', 'MF', 13, 26),
('ply_nzl_13', 'nzl', 'Nando Pijnaker', 'DF', 14, 26),
('ply_nzl_14', 'nzl', 'Bill Tuiloma', 'DF', 15, 31),
('ply_nzl_15', 'nzl', 'Alex Paulsen', 'GK', 16, 23),
('ply_nzl_16', 'nzl', 'Joe Bell', 'MF', 17, 26),
('ply_nzl_17', 'nzl', 'Cameron Howieson', 'MF', 18, 32),
('ply_nzl_18', 'nzl', 'Oskar Zawada', 'FW', 19, 28),
('ply_nzl_19', 'nzl', 'Finn Surman', 'DF', 20, 23),
('ply_nzl_20', 'nzl', 'Max Crocombe', 'GK', 21, 32),
('ply_nzl_21', 'nzl', 'Tim Payne', 'DF', 22, 30),
('ply_nzl_22', 'nzl', 'Clayton Lewis', 'MF', 23, 27),
('ply_nzl_23', 'nzl', 'Kosta de Keram', 'FW', 2, 24),

-- ==================== UEFA ====================

-- Austria (aut) - Captain: David Alaba
('ply_aut_01', 'aut', 'David Alaba', 'DF', 8, 33),
('ply_aut_02', 'aut', 'Daniel Bachmann', 'GK', 1, 31),
('ply_aut_03', 'aut', 'Marcel Sabitzer', 'MF', 9, 32),
('ply_aut_04', 'aut', 'Konrad Laimer', 'MF', 6, 28),
('ply_aut_05', 'aut', 'Xaver Schlager', 'MF', 10, 27),
('ply_aut_06', 'aut', 'Christoph Baumgartner', 'MF', 19, 26),
('ply_aut_07', 'aut', 'Marko Arnautović', 'FW', 7, 37),
('ply_aut_08', 'aut', 'Michael Gregoritsch', 'FW', 11, 32),
('ply_aut_09', 'aut', 'Patrick Wimmer', 'FW', 22, 25),
('ply_aut_10', 'aut', 'Philipp Lienhart', 'DF', 4, 29),
('ply_aut_11', 'aut', 'Stefan Posch', 'DF', 5, 29),
('ply_aut_12', 'aut', 'Maximilian Wöber', 'DF', 2, 27),
('ply_aut_13', 'aut', 'Alexander Prass', 'MF', 14, 24),
('ply_aut_14', 'aut', 'Nicolas Seiwald', 'MF', 13, 25),
('ply_aut_15', 'aut', 'Heinz Lindner', 'GK', 12, 35),
('ply_aut_16', 'aut', 'Andreas Weimann', 'FW', 18, 35),
('ply_aut_17', 'aut', 'Florian Grillitsch', 'MF', 15, 30),
('ply_aut_18', 'aut', 'Kevin Danso', 'DF', 3, 27),
('ply_aut_19', 'aut', 'Leopold Querfeld', 'DF', 20, 22),
('ply_aut_20', 'aut', 'Marco Friedl', 'DF', 16, 27),
('ply_aut_21', 'aut', 'Sasa Kalajdzic', 'FW', 17, 28),
('ply_aut_22', 'aut', 'Patrick Pentz', 'GK', 21, 28),
('ply_aut_23', 'aut', 'Dejan Ljubicic', 'MF', 23, 28),

-- Belgium (bel) - Captain: Kevin De Bruyne
('ply_bel_01', 'bel', 'Kevin De Bruyne', 'MF', 7, 35),
('ply_bel_02', 'bel', 'Thibaut Courtois', 'GK', 1, 34),
('ply_bel_03', 'bel', 'Romelu Lukaku', 'FW', 9, 33),
('ply_bel_04', 'bel', 'Jan Vertonghen', 'DF', 5, 39),
('ply_bel_05', 'bel', 'Toby Alderweireld', 'DF', 4, 37),
('ply_bel_06', 'bel', 'Axel Witsel', 'MF', 6, 37),
('ply_bel_07', 'bel', 'Youri Tielemans', 'MF', 8, 28),
('ply_bel_08', 'bel', 'Jeremy Doku', 'FW', 11, 23),
('ply_bel_09', 'bel', 'Loïs Openda', 'FW', 10, 26),
('ply_bel_10', 'bel', 'Amadou Onana', 'MF', 15, 24),
('ply_bel_11', 'bel', 'Timothy Castagne', 'DF', 2, 30),
('ply_bel_12', 'bel', 'Wout Faes', 'DF', 3, 27),
('ply_bel_13', 'bel', 'Dries Mertens', 'FW', 14, 39),
('ply_bel_14', 'bel', 'Yannick Carrasco', 'FW', 16, 32),
('ply_bel_15', 'bel', 'Leandro Trossard', 'FW', 17, 31),
('ply_bel_16', 'bel', 'Matz Sels', 'GK', 12, 33),
('ply_bel_17', 'bel', 'Arthur Theate', 'DF', 18, 25),
('ply_bel_18', 'bel', 'Orel Mangala', 'MF', 19, 27),
('ply_bel_19', 'bel', 'Charles De Ketelaere', 'FW', 20, 25),
('ply_bel_20', 'bel', 'Zeno Debast', 'DF', 21, 22),
('ply_bel_21', 'bel', 'Johan Bakayoko', 'FW', 22, 23),
('ply_bel_22', 'bel', 'Aster Vranckx', 'MF', 23, 23),
('ply_bel_23', 'bel', 'Simon Mignolet', 'GK', 13, 38),

-- Bosnia and Herzegovina (bih) - Captain: Edin Dzeko
('ply_bih_01', 'bih', 'Edin Dzeko', 'FW', 9, 40),
('ply_bih_02', 'bih', 'Ibrahim Sehic', 'GK', 1, 37),
('ply_bih_03', 'bih', 'Amar Dedic', 'DF', 2, 22),
('ply_bih_04', 'bih', 'Anel Ahmedhodzic', 'DF', 4, 27),
('ply_bih_05', 'bih', 'Dennis Hadzikadunic', 'DF', 5, 27),
('ply_bih_06', 'bih', 'Sead Kolasinac', 'DF', 6, 32),
('ply_bih_07', 'bih', 'Miralem Pjanic', 'MF', 8, 36),
('ply_bih_08', 'bih', 'Rade Krunic', 'MF', 10, 32),
('ply_bih_09', 'bih', 'Smail Prevljak', 'FW', 11, 30),
('ply_bih_10', 'bih', 'Ermedin Demirovic', 'FW', 7, 27),
('ply_bih_11', 'bih', 'Haris Hajradinovic', 'MF', 14, 31),
('ply_bih_12', 'bih', 'Amir Hadziahmetovic', 'MF', 15, 28),
('ply_bih_13', 'bih', 'Gojko Cimirot', 'MF', 16, 32),
('ply_bih_14', 'bih', 'Kenan Kodro', 'FW', 17, 31),
('ply_bih_15', 'bih', 'Adnan Kovacevic', 'DF', 18, 31),
('ply_bih_16', 'bih', 'Nikola Vasilj', 'GK', 12, 29),
('ply_bih_17', 'bih', 'Luka Menalo', 'FW', 19, 28),
('ply_bih_18', 'bih', 'Dino Hotic', 'MF', 20, 30),
('ply_bih_19', 'bih', 'Benjamin Tahirovic', 'MF', 21, 22),
('ply_bih_20', 'bih', 'Sanjin Hasic', 'DF', 22, 28),
('ply_bih_21', 'bih', 'Nihad Mujakic', 'DF', 23, 27),
('ply_bih_22', 'bih', 'Dal Varešanović', 'MF', 13, 25),
('ply_bih_23', 'bih', 'Kenan Piric', 'GK', 24, 31),

-- Croatia (cro) - Captain: Luka Modric
('ply_cro_01', 'cro', 'Luka Modric', 'MF', 10, 40),
('ply_cro_02', 'cro', 'Dominik Livakovic', 'GK', 1, 31),
('ply_cro_03', 'cro', 'Josko Gvardiol', 'DF', 4, 24),
('ply_cro_04', 'cro', 'Marcelo Brozovic', 'MF', 11, 33),
('ply_cro_05', 'cro', 'Mateo Kovacic', 'MF', 8, 32),
('ply_cro_06', 'cro', 'Andrej Kramaric', 'FW', 9, 34),
('ply_cro_07', 'cro', 'Bruno Petkovic', 'FW', 17, 31),
('ply_cro_08', 'cro', 'Josip Sutalo', 'DF', 6, 25),
('ply_cro_09', 'cro', 'Borna Sosa', 'DF', 3, 28),
('ply_cro_10', 'cro', 'Mario Pasalic', 'MF', 15, 30),
('ply_cro_11', 'cro', 'Ante Budimir', 'FW', 14, 33),
('ply_cro_12', 'cro', 'Lovro Majer', 'MF', 7, 27),
('ply_cro_13', 'cro', 'Ivan Perisic', 'FW', 4, 37),
('ply_cro_14', 'cro', 'Josip Stanisic', 'DF', 2, 26),
('ply_cro_15', 'cro', 'Mislav Orsic', 'FW', 18, 33),
('ply_cro_16', 'cro', 'Nediljko Labrovic', 'GK', 12, 26),
('ply_cro_17', 'cro', 'Borna Barisic', 'DF', 5, 33),
('ply_cro_18', 'cro', 'Luka Sucic', 'MF', 20, 23),
('ply_cro_19', 'cro', 'Martin Erlic', 'DF', 13, 27),
('ply_cro_20', 'cro', 'Petar Musa', 'FW', 19, 28),
('ply_cro_21', 'cro', 'Marko Livaja', 'FW', 11, 32),
('ply_cro_22', 'cro', 'Pavel Sucic', 'MF', 21, 22),
('ply_cro_23', 'cro', 'Ivo Grbic', 'GK', 23, 30),

-- Czech Republic (cze) - Captain: Tomas Soucek
('ply_cze_01', 'cze', 'Tomas Soucek', 'MF', 22, 31),
('ply_cze_02', 'cze', 'Jindrich Stanek', 'GK', 1, 30),
('ply_cze_03', 'cze', 'Vladimir Coufal', 'DF', 5, 33),
('ply_cze_04', 'cze', 'David Zima', 'DF', 3, 24),
('ply_cze_05', 'cze', 'Tomas Holes', 'DF', 4, 31),
('ply_cze_06', 'cze', 'Antonin Barak', 'MF', 7, 31),
('ply_cze_07', 'cze', 'Patrik Schick', 'FW', 10, 30),
('ply_cze_08', 'cze', 'Jakub Jankto', 'MF', 8, 30),
('ply_cze_09', 'cze', 'Adam Hlozek', 'FW', 9, 23),
('ply_cze_10', 'cze', 'Vaclav Cerny', 'FW', 11, 28),
('ply_cze_11', 'cze', 'Lukas Provod', 'MF', 14, 29),
('ply_cze_12', 'cze', 'Pavel Kaderabek', 'DF', 2, 33),
('ply_cze_13', 'cze', 'Matej Kovar', 'GK', 12, 26),
('ply_cze_14', 'cze', 'Tomas Petrasek', 'DF', 6, 33),
('ply_cze_15', 'cze', 'Ondrej Lingr', 'MF', 15, 27),
('ply_cze_16', 'cze', 'Jan Kuchta', 'FW', 17, 28),
('ply_cze_17', 'cze', 'David Doudera', 'DF', 18, 27),
('ply_cze_18', 'cze', 'Ladislav Krejci', 'DF', 19, 32),
('ply_cze_19', 'cze', 'Mojmir Chytil', 'FW', 20, 26),
('ply_cze_20', 'cze', 'Tomas Pekhart', 'FW', 21, 36),
('ply_cze_21', 'cze', 'Filip Panak', 'DF', 23, 29),
('ply_cze_22', 'cze', 'Petr Sevcik', 'MF', 13, 31),
('ply_cze_23', 'cze', 'Ales Mandous', 'GK', 16, 33),

-- England (eng) - Captain: Harry Kane
('ply_eng_01', 'eng', 'Harry Kane', 'FW', 9, 32),
('ply_eng_02', 'eng', 'Jordan Pickford', 'GK', 1, 32),
('ply_eng_03', 'eng', 'John Stones', 'DF', 5, 32),
('ply_eng_04', 'eng', 'Kyle Walker', 'DF', 2, 36),
('ply_eng_05', 'eng', 'Luke Shaw', 'DF', 3, 30),
('ply_eng_06', 'eng', 'Declan Rice', 'MF', 4, 27),
('ply_eng_07', 'eng', 'Jude Bellingham', 'MF', 10, 23),
('ply_eng_08', 'eng', 'Phil Foden', 'FW', 11, 26),
('ply_eng_09', 'eng', 'Bukayo Saka', 'FW', 7, 24),
('ply_eng_10', 'eng', 'Cole Palmer', 'MF', 8, 24),
('ply_eng_11', 'eng', 'Marcus Rashford', 'FW', 12, 28),
('ply_eng_12', 'eng', 'Anthony Gordon', 'FW', 14, 24),
('ply_eng_13', 'eng', 'Ezri Konsa', 'DF', 6, 28),
('ply_eng_14', 'eng', 'Marc Guehi', 'DF', 15, 25),
('ply_eng_15', 'eng', 'Kobbie Mainoo', 'MF', 16, 21),
('ply_eng_16', 'eng', 'Dean Henderson', 'GK', 13, 29),
('ply_eng_17', 'eng', 'Reece James', 'DF', 17, 26),
('ply_eng_18', 'eng', 'Lewis Hall', 'DF', 18, 21),
('ply_eng_19', 'eng', 'Morgan Rogers', 'MF', 19, 23),
('ply_eng_20', 'eng', 'Eberechi Eze', 'MF', 20, 27),
('ply_eng_21', 'eng', 'Noni Madueke', 'FW', 21, 23),
('ply_eng_22', 'eng', 'Jarrod Bowen', 'FW', 22, 29),
('ply_eng_23', 'eng', 'James Trafford', 'GK', 23, 23),

-- France (fra) - Captain: Kylian Mbappe
('ply_fra_01', 'fra', 'Kylian Mbappe', 'FW', 10, 27),
('ply_fra_02', 'fra', 'Mike Maignan', 'GK', 1, 30),
('ply_fra_03', 'fra', 'William Saliba', 'DF', 4, 25),
('ply_fra_04', 'fra', 'Dayot Upamecano', 'DF', 5, 27),
('ply_fra_05', 'fra', 'Theo Hernandez', 'DF', 3, 28),
('ply_fra_06', 'fra', 'Eduardo Camavinga', 'MF', 6, 23),
('ply_fra_07', 'fra', 'Aurelien Tchouameni', 'MF', 8, 26),
('ply_fra_08', 'fra', 'Ousmane Dembele', 'FW', 7, 29),
('ply_fra_09', 'fra', 'Randal Kolo Muani', 'FW', 9, 27),
('ply_fra_10', 'fra', 'Marcus Thuram', 'FW', 11, 28),
('ply_fra_11', 'fra', 'Adrien Rabiot', 'MF', 14, 31),
('ply_fra_12', 'fra', 'Kingsley Coman', 'FW', 12, 29),
('ply_fra_13', 'fra', 'Ibrahima Konate', 'DF', 13, 27),
('ply_fra_14', 'fra', 'Jules Kounde', 'DF', 15, 27),
('ply_fra_15', 'fra', 'Warren Zaire-Emery', 'MF', 16, 20),
('ply_fra_16', 'fra', 'Brice Samba', 'GK', 23, 32),
('ply_fra_17', 'fra', 'Lucas Hernandez', 'DF', 17, 30),
('ply_fra_18', 'fra', 'Christopher Nkunku', 'FW', 18, 28),
('ply_fra_19', 'fra', 'Desire Doue', 'MF', 19, 20),
('ply_fra_20', 'fra', 'Michael Olise', 'FW', 20, 24),
('ply_fra_21', 'fra', 'Rayan Cherki', 'MF', 21, 22),
('ply_fra_22', 'fra', 'Hugo Ekitike', 'FW', 22, 23),
('ply_fra_23', 'fra', 'Lucas Chevalier', 'GK', 2, 23),

-- Germany (ger) - Captain: Ilkay Gundogan
('ply_ger_01', 'ger', 'Ilkay Gundogan', 'MF', 8, 35),
('ply_ger_02', 'ger', 'Manuel Neuer', 'GK', 1, 40),
('ply_ger_03', 'ger', 'Joshua Kimmich', 'MF', 6, 31),
('ply_ger_04', 'ger', 'Antonio Rudiger', 'DF', 4, 33),
('ply_ger_05', 'ger', 'Kai Havertz', 'FW', 7, 27),
('ply_ger_06', 'ger', 'Jamal Musiala', 'MF', 10, 23),
('ply_ger_07', 'ger', 'Florian Wirtz', 'MF', 11, 23),
('ply_ger_08', 'ger', 'Leroy Sane', 'FW', 9, 30),
('ply_ger_09', 'ger', 'Niclas Fullkrug', 'FW', 14, 33),
('ply_ger_10', 'ger', 'Jonathan Tah', 'DF', 5, 29),
('ply_ger_11', 'ger', 'Serge Gnabry', 'FW', 13, 30),
('ply_ger_12', 'ger', 'Timo Werner', 'FW', 15, 30),
('ply_ger_13', 'ger', 'Robin Gosens', 'DF', 3, 31),
('ply_ger_14', 'ger', 'Aleksandar Pavlovic', 'MF', 16, 22),
('ply_ger_15', 'ger', 'Marc-Andre ter Stegen', 'GK', 12, 34),
('ply_ger_16', 'ger', 'Maximilian Mittelstadt', 'DF', 2, 28),
('ply_ger_17', 'ger', 'Waldemar Anton', 'DF', 17, 29),
('ply_ger_18', 'ger', 'Pascal Gross', 'MF', 18, 35),
('ply_ger_19', 'ger', 'Deniz Undav', 'FW', 19, 29),
('ply_ger_20', 'ger', 'Robert Andrich', 'MF', 20, 31),
('ply_ger_21', 'ger', 'Chris Fuhrich', 'MF', 21, 28),
('ply_ger_22', 'ger', 'Nico Schlotterbeck', 'DF', 22, 26),
('ply_ger_23', 'ger', 'Oliver Baumann', 'GK', 23, 35),

-- Netherlands (ned) - Captain: Virgil van Dijk
('ply_ned_01', 'ned', 'Virgil van Dijk', 'DF', 4, 34),
('ply_ned_02', 'ned', 'Bart Verbruggen', 'GK', 1, 23),
('ply_ned_03', 'ned', 'Nathan Aké', 'DF', 5, 31),
('ply_ned_04', 'ned', 'Matthijs de Ligt', 'DF', 3, 27),
('ply_ned_05', 'ned', 'Frenkie de Jong', 'MF', 8, 29),
('ply_ned_06', 'ned', 'Cody Gakpo', 'FW', 9, 27),
('ply_ned_07', 'ned', 'Memphis Depay', 'FW', 10, 32),
('ply_ned_08', 'ned', 'Xavi Simons', 'MF', 7, 23),
('ply_ned_09', 'ned', 'Steven Bergwijn', 'FW', 11, 28),
('ply_ned_10', 'ned', 'Denzel Dumfries', 'DF', 2, 29),
('ply_ned_11', 'ned', 'Ryan Gravenberch', 'MF', 6, 23),
('ply_ned_12', 'ned', 'Tijjani Reijnders', 'MF', 12, 27),
('ply_ned_13', 'ned', 'Wout Weghorst', 'FW', 14, 33),
('ply_ned_14', 'ned', 'Quinten Timber', 'MF', 15, 23),
('ply_ned_15', 'ned', 'Micky van de Ven', 'DF', 16, 24),
('ply_ned_16', 'ned', 'Mark Flekken', 'GK', 13, 32),
('ply_ned_17', 'ned', 'Daley Blind', 'DF', 17, 36),
('ply_ned_18', 'ned', 'Brian Brobbey', 'FW', 18, 23),
('ply_ned_19', 'ned', 'Joey Veerman', 'MF', 19, 26),
('ply_ned_20', 'ned', 'Jerdy Schouten', 'MF', 20, 28),
('ply_ned_21', 'ned', 'Noa Lang', 'FW', 21, 26),
('ply_ned_22', 'ned', 'Jeremie Frimpong', 'DF', 22, 25),
('ply_ned_23', 'ned', 'Justin Bijlow', 'GK', 23, 28),

-- Norway (nor) - Captain: Martin Odegaard  (ya corregido)
('ply_nor_01', 'nor', 'Martin Odegaard', 'MF', 10, 27),
('ply_nor_02', 'nor', 'Orjan Nyland', 'GK', 1, 35),
('ply_nor_03', 'nor', 'Erling Haaland', 'FW', 9, 25),
('ply_nor_04', 'nor', 'Alexander Sorloth', 'FW', 11, 30),
('ply_nor_05', 'nor', 'Kristoffer Ajer', 'DF', 4, 28),
('ply_nor_06', 'nor', 'Leo Ostigard', 'DF', 5, 26),
('ply_nor_07', 'nor', 'Mohamed Elyounoussi', 'FW', 7, 31),
('ply_nor_08', 'nor', 'Oscar Bobb', 'FW', 17, 22),
('ply_nor_09', 'nor', 'Andreas Hanche-Olsen', 'DF', 3, 28),
('ply_nor_10', 'nor', 'Sander Berge', 'MF', 8, 28),
('ply_nor_11', 'nor', 'Jonas Svensson', 'DF', 2, 32),
('ply_nor_12', 'nor', 'Birger Meling', 'DF', 6, 31),
('ply_nor_13', 'nor', 'Patrick Berg', 'MF', 14, 27),
('ply_nor_14', 'nor', 'Julian Ryerson', 'DF', 20, 28),
('ply_nor_15', 'nor', 'Kristian Thorstvedt', 'MF', 18, 27),
('ply_nor_16', 'nor', 'Egil Selvik', 'GK', 12, 27),
('ply_nor_17', 'nor', 'Fredrik Aursnes', 'MF', 15, 30),
('ply_nor_18', 'nor', 'Jorgen Strand Larsen', 'FW', 23, 26),
('ply_nor_19', 'nor', 'Arne Engels', 'MF', 16, 25),
('ply_nor_20', 'nor', 'Marcus Pedersen', 'DF', 22, 25),
('ply_nor_21', 'nor', 'Stian Gregersen', 'DF', 21, 30),
('ply_nor_22', 'nor', 'Mathias Normann', 'MF', 19, 29),
('ply_nor_23', 'nor', 'Hugo Vetlesen', 'MF', 13, 25),

-- Portugal (por) - Captain: Bruno Fernandes
('ply_por_01', 'por', 'Bruno Fernandes', 'MF', 8, 31),
('ply_por_02', 'por', 'Diogo Costa', 'GK', 1, 26),
('ply_por_03', 'por', 'Ruben Dias', 'DF', 4, 29),
('ply_por_04', 'por', 'Pepe', 'DF', 3, 43),
('ply_por_05', 'por', 'Joao Cancelo', 'DF', 2, 32),
('ply_por_06', 'por', 'Bernardo Silva', 'MF', 10, 31),
('ply_por_07', 'por', 'Cristiano Ronaldo', 'FW', 7, 41),
('ply_por_08', 'por', 'Rafael Leão', 'FW', 11, 26),
('ply_por_09', 'por', 'Goncalo Ramos', 'FW', 9, 24),
('ply_por_10', 'por', 'Vitinha', 'MF', 6, 26),
('ply_por_11', 'por', 'Joao Felix', 'FW', 14, 26),
('ply_por_12', 'por', 'Otavio', 'MF', 15, 30),
('ply_por_13', 'por', 'Diogo Dalot', 'DF', 5, 26),
('ply_por_14', 'por', 'Nuno Mendes', 'DF', 12, 23),
('ply_por_15', 'por', 'Ruben Neves', 'MF', 13, 29),
('ply_por_16', 'por', 'Jose Sa', 'GK', 16, 32),
('ply_por_17', 'por', 'Antonio Silva', 'DF', 17, 22),
('ply_por_18', 'por', 'Matheus Nunes', 'MF', 18, 27),
('ply_por_19', 'por', 'Pedro Neto', 'FW', 19, 26),
('ply_por_20', 'por', 'Goncalo Inacio', 'DF', 20, 24),
('ply_por_21', 'por', 'Diogo Jota', 'FW', 21, 29),
('ply_por_22', 'por', 'Joao Palhinha', 'MF', 22, 29),
('ply_por_23', 'por', 'Rui Patricio', 'GK', 23, 38),

-- Scotland (sco) - Captain: Andrew Robertson
('ply_sco_01', 'sco', 'Andrew Robertson', 'DF', 3, 32),
('ply_sco_02', 'sco', 'Craig Gordon', 'GK', 1, 42),
('ply_sco_03', 'sco', 'Kieran Tierney', 'DF', 5, 29),
('ply_sco_04', 'sco', 'Scott McTominay', 'MF', 4, 29),
('ply_sco_05', 'sco', 'John McGinn', 'MF', 7, 31),
('ply_sco_06', 'sco', 'Che Adams', 'FW', 9, 29),
('ply_sco_07', 'sco', 'Lyndon Dykes', 'FW', 10, 30),
('ply_sco_08', 'sco', 'Billy Gilmour', 'MF', 8, 24),
('ply_sco_09', 'sco', 'Callum McGregor', 'MF', 6, 32),
('ply_sco_10', 'sco', 'Aaron Hickey', 'DF', 2, 23),
('ply_sco_11', 'sco', 'Nathan Patterson', 'DF', 12, 24),
('ply_sco_12', 'sco', 'Grant Hanley', 'DF', 13, 33),
('ply_sco_13', 'sco', 'Liam Cooper', 'DF', 15, 34),
('ply_sco_14', 'sco', 'Ryan Jack', 'MF', 16, 33),
('ply_sco_15', 'sco', 'Ché Adams', 'FW', 11, 29),
('ply_sco_16', 'sco', 'Zander Clark', 'GK', 17, 33),
('ply_sco_17', 'sco', 'Scott McKenna', 'DF', 18, 28),
('ply_sco_18', 'sco', 'Kenny McLean', 'MF', 19, 34),
('ply_sco_19', 'sco', 'Ryan Christie', 'MF', 20, 30),
('ply_sco_20', 'sco', 'Lewis Ferguson', 'MF', 21, 26),
('ply_sco_21', 'sco', 'Lawrence Shankland', 'FW', 22, 30),
('ply_sco_22', 'sco', 'Greg Taylor', 'DF', 23, 28),
('ply_sco_23', 'sco', 'Liam Kelly', 'GK', 24, 30),

-- Spain (esp) - Captain: Alvaro Morata
('ply_esp_01', 'esp', 'Alvaro Morata', 'FW', 7, 33),
('ply_esp_02', 'esp', 'Unai Simon', 'GK', 1, 29),
('ply_esp_03', 'esp', 'Aymeric Laporte', 'DF', 4, 32),
('ply_esp_04', 'esp', 'Rodri', 'MF', 5, 30),
('ply_esp_05', 'esp', 'Pedri', 'MF', 8, 23),
('ply_esp_06', 'esp', 'Lamine Yamal', 'FW', 10, 18),
('ply_esp_07', 'esp', 'Nico Williams', 'FW', 11, 22),
('ply_esp_08', 'esp', 'Dani Carvajal', 'DF', 2, 34),
('ply_esp_09', 'esp', 'Dani Olmo', 'MF', 6, 28),
('ply_esp_10', 'esp', 'Ferran Torres', 'FW', 9, 26),
('ply_esp_11', 'esp', 'Alejandro Balde', 'DF', 3, 22),
('ply_esp_12', 'esp', 'Martin Zubimendi', 'MF', 12, 26),
('ply_esp_13', 'esp', 'Mikel Merino', 'MF', 14, 29),
('ply_esp_14', 'esp', 'Robin Le Normand', 'DF', 15, 29),
('ply_esp_15', 'esp', 'Marc Cucurella', 'DF', 16, 27),
('ply_esp_16', 'esp', 'David Raya', 'GK', 13, 30),
('ply_esp_17', 'esp', 'Joselu', 'FW', 17, 36),
('ply_esp_18', 'esp', 'Fabian Ruiz', 'MF', 18, 30),
('ply_esp_19', 'esp', 'Jesus Navas', 'DF', 19, 40),
('ply_esp_20', 'esp', 'Inigo Martinez', 'DF', 20, 34),
('ply_esp_21', 'esp', 'Mikel Oyarzabal', 'FW', 21, 29),
('ply_esp_22', 'esp', 'Alex Baena', 'MF', 22, 24),
('ply_esp_23', 'esp', 'Robert Sanchez', 'GK', 23, 28),

-- Sweden (swe) - Captain: Emil Forsberg
('ply_swe_01', 'swe', 'Emil Forsberg', 'MF', 10, 34),
('ply_swe_02', 'swe', 'Robin Olsen', 'GK', 1, 36),
('ply_swe_03', 'swe', 'Victor Lindelof', 'DF', 4, 31),
('ply_swe_04', 'swe', 'Alexander Isak', 'FW', 9, 26),
('ply_swe_05', 'swe', 'Anthony Elanga', 'FW', 7, 24),
('ply_swe_06', 'swe', 'Dejan Kulusevski', 'FW', 11, 26),
('ply_swe_07', 'swe', 'Viktor Claesson', 'MF', 8, 34),
('ply_swe_08', 'swe', 'Kristoffer Olsson', 'MF', 6, 30),
('ply_swe_09', 'swe', 'Jesper Karlsson', 'FW', 12, 27),
('ply_swe_10', 'swe', 'Marcus Danielson', 'DF', 5, 36),
('ply_swe_11', 'swe', 'Ludwig Augustinsson', 'DF', 3, 32),
('ply_swe_12', 'swe', 'Pontus Jansson', 'DF', 2, 35),
('ply_swe_13', 'swe', 'Isak Hien', 'DF', 13, 26),
('ply_swe_14', 'swe', 'Jens Cajuste', 'MF', 14, 27),
('ply_swe_15', 'swe', 'Gustav Svensson', 'MF', 15, 38),
('ply_swe_16', 'swe', 'Kristoffer Nordfeldt', 'GK', 16, 36),
('ply_swe_17', 'swe', 'Viktor Gyokeres', 'FW', 17, 28),
('ply_swe_18', 'swe', 'Mattias Svanberg', 'MF', 18, 27),
('ply_swe_19', 'swe', 'Hugo Larsson', 'MF', 19, 21),
('ply_swe_20', 'swe', 'Joel Andersson', 'DF', 20, 29),
('ply_swe_21', 'swe', 'Emil Holm', 'DF', 21, 25),
('ply_swe_22', 'swe', 'Sebastian Nanasi', 'MF', 22, 23),
('ply_swe_23', 'swe', 'Filip Djuricic', 'MF', 23, 33),

-- Switzerland (sui) - Captain: Granit Xhaka
('ply_sui_01', 'sui', 'Granit Xhaka', 'MF', 10, 33),
('ply_sui_02', 'sui', 'Yann Sommer', 'GK', 1, 37),
('ply_sui_03', 'sui', 'Manuel Akanji', 'DF', 4, 30),
('ply_sui_04', 'sui', 'Ricardo Rodriguez', 'DF', 5, 33),
('ply_sui_05', 'sui', 'Fabian Schär', 'DF', 3, 34),
('ply_sui_06', 'sui', 'Breel Embolo', 'FW', 7, 29),
('ply_sui_07', 'sui', 'Xherdan Shaqiri', 'FW', 8, 34),
('ply_sui_08', 'sui', 'Remo Freuler', 'MF', 6, 33),
('ply_sui_09', 'sui', 'Denis Zakaria', 'MF', 9, 29),
('ply_sui_10', 'sui', 'Ruben Vargas', 'FW', 11, 27),
('ply_sui_11', 'sui', 'Noah Okafor', 'FW', 12, 25),
('ply_sui_12', 'sui', 'Silvan Widmer', 'DF', 2, 33),
('ply_sui_13', 'sui', 'Nico Elvedi', 'DF', 13, 29),
('ply_sui_14', 'sui', 'Steven Zuber', 'FW', 14, 34),
('ply_sui_15', 'sui', 'Gregor Kobel', 'GK', 15, 28),
('ply_sui_16', 'sui', 'Edimilson Fernandes', 'MF', 16, 29),
('ply_sui_17', 'sui', 'Zeki Amdouni', 'FW', 17, 24),
('ply_sui_18', 'sui', 'Dan Ndoye', 'FW', 18, 25),
('ply_sui_19', 'sui', 'Fabian Rieder', 'MF', 19, 23),
('ply_sui_20', 'sui', 'Leonidas Stergiou', 'DF', 20, 23),
('ply_sui_21', 'sui', 'Michael Lang', 'DF', 21, 34),
('ply_sui_22', 'sui', 'Ardon Jashari', 'MF', 22, 23),
('ply_sui_23', 'sui', 'Philipp Kohn', 'GK', 23, 27),

-- Turkey (tur) - Captain: Hakan Calhanoglu
('ply_tur_01', 'tur', 'Hakan Calhanoglu', 'MF', 8, 32),
('ply_tur_02', 'tur', 'Ugurcan Cakir', 'GK', 1, 30),
('ply_tur_03', 'tur', 'Merih Demiral', 'DF', 4, 28),
('ply_tur_04', 'tur', 'Caglar Soyuncu', 'DF', 5, 30),
('ply_tur_05', 'tur', 'Ferdi Kadioglu', 'DF', 2, 26),
('ply_tur_06', 'tur', 'Arda Guler', 'MF', 10, 21),
('ply_tur_07', 'tur', 'Burak Yilmaz', 'FW', 7, 40),
('ply_tur_08', 'tur', 'Yunus Akgun', 'FW', 9, 25),
('ply_tur_09', 'tur', 'Kenan Yildiz', 'FW', 11, 21),
('ply_tur_10', 'tur', 'Orkun Kokcu', 'MF', 6, 25),
('ply_tur_11', 'tur', 'Salih Ozcan', 'MF', 12, 27),
('ply_tur_12', 'tur', 'Altay Bayindir', 'GK', 13, 28),
('ply_tur_13', 'tur', 'Abdulkadir Omur', 'MF', 14, 26),
('ply_tur_14', 'tur', 'Enes Unal', 'FW', 15, 28),
('ply_tur_15', 'tur', 'Zeki Celik', 'DF', 3, 29),
('ply_tur_16', 'tur', 'Ozan Kabak', 'DF', 16, 25),
('ply_tur_17', 'tur', 'Berkan Kutlu', 'MF', 17, 27),
('ply_tur_18', 'tur', 'Kerem Akturkoglu', 'FW', 18, 27),
('ply_tur_19', 'tur', 'Cengiz Under', 'FW', 19, 28),
('ply_tur_20', 'tur', 'Okay Yokuslu', 'MF', 20, 32),
('ply_tur_21', 'tur', 'Semih Kilicsoy', 'FW', 21, 20),
('ply_tur_22', 'tur', 'Samet Akaydin', 'DF', 22, 30),
('ply_tur_23', 'tur', 'Mert Gunok', 'GK', 23, 37);

-- Player attributes for match engine
-- Range rules:
-- skill: 50..99
-- defense: 50..99
-- attack: 50..99
-- energy: 70..99
-- Team rating influence:
-- - Every player receives a team-level offset based on (rating - 80).
-- - This keeps lower/higher teams separated while preserving per-position randomness.
UPDATE team_players
SET
  skill = MIN(
    99,
    MAX(
      50,
      (
        CASE
          WHEN position = 'GK' THEN 64 + ABS(RANDOM()) % 18
          ELSE 60 + ABS(RANDOM()) % 22
        END
      ) + CAST(
        ROUND(((SELECT rating FROM teams WHERE teams.teamId = team_players.teamId) - 80) * 0.7) AS INTEGER
      )
    )
  ),
  attack = MIN(
    99,
    MAX(
      50,
      (
        CASE
          WHEN position = 'FW' THEN 68 + ABS(RANDOM()) % 20
          WHEN position = 'MF' THEN 60 + ABS(RANDOM()) % 20
          WHEN position = 'DF' THEN 54 + ABS(RANDOM()) % 20
          ELSE 52 + ABS(RANDOM()) % 16
        END
      ) + CAST(
        ROUND(((SELECT rating FROM teams WHERE teams.teamId = team_players.teamId) - 80) * 0.9) AS INTEGER
      )
    )
  ),
  defense = MIN(
    99,
    MAX(
      50,
      (
        CASE
          WHEN position = 'GK' THEN 82 + ABS(RANDOM()) % 14
          WHEN position = 'DF' THEN 68 + ABS(RANDOM()) % 20
          WHEN position = 'MF' THEN 60 + ABS(RANDOM()) % 18
          ELSE 52 + ABS(RANDOM()) % 18
        END
      ) + CAST(
        ROUND(((SELECT rating FROM teams WHERE teams.teamId = team_players.teamId) - 80) * 0.9) AS INTEGER
      )
    )
  ),
  energy = 70 + ABS(RANDOM()) % 30;

-- Captain boost:
-- keep captain core attributes high, still influenced by team rating.
UPDATE team_players
SET
  skill = MIN(
    99,
    MAX(
      70,
      74 + ABS(RANDOM()) % 18 + CAST(
        ROUND(((SELECT rating FROM teams WHERE teams.teamId = team_players.teamId) - 80) * 0.6) AS INTEGER
      )
    )
  ),
  attack = MIN(
    99,
    MAX(
      70,
      74 + ABS(RANDOM()) % 18 + CAST(
        ROUND(((SELECT rating FROM teams WHERE teams.teamId = team_players.teamId) - 80) * 0.6) AS INTEGER
      )
    )
  ),
  defense = MIN(
    99,
    MAX(
      70,
      74 + ABS(RANDOM()) % 18 + CAST(
        ROUND(((SELECT rating FROM teams WHERE teams.teamId = team_players.teamId) - 80) * 0.6) AS INTEGER
      )
    )
  )
WHERE EXISTS (
  SELECT 1
  FROM teams
  WHERE teams.teamId = team_players.teamId
    AND LOWER(TRIM(teams.captain)) = LOWER(TRIM(team_players.name))
);

UPDATE team_players SET lastUpdate = datetime('now') WHERE 1=1;
