import { Injectable } from '@nestjs/common';
import {
  ALL_FORMATIONS,
  ALL_STRATEGIES,
  STRATEGY_COMPATIBILITY,
} from './match-tactical.config';
import { MatchFormation } from '../model/match-formation.enum';
import { MatchStrategy } from '../model/match-strategy.enum';
import { TacticalLineBoost, TacticalSnapshot } from '../interfaces/match-service.interfaces';

@Injectable()
/**
 * Tactical helper for strategy/formation parsing and tactical snapshot composition.
 */
export class MatchTacticalHelper {
  /**
   * Computes tactical state used by probability and possession functions.
   */
  buildTacticalSnapshot(params: {
    strategy: string | null;
    formation: string | null;
    opponentStrategy: string | null;
    opponentFormation: string | null;
  }): TacticalSnapshot {
    const teamStrategy = this.parseStrategy(params.strategy);
    const teamFormation = this.parseFormation(params.formation);
    const opponentStrategy = this.parseStrategy(params.opponentStrategy);
    const opponentFormation = this.parseFormation(params.opponentFormation);

    const teamPenaltyPoints = this.resolveCompatibilityPenaltyPoints(teamStrategy, teamFormation);
    const opponentPenaltyPoints = this.resolveCompatibilityPenaltyPoints(
      opponentStrategy,
      opponentFormation,
    );

    return {
      teamStrategy,
      teamFormation,
      opponentStrategy,
      opponentFormation,
      teamPenaltyPoints,
      opponentPenaltyPoints,
      teamLine: this.resolveLineBoost(teamStrategy),
      opponentLine: this.resolveLineBoost(opponentStrategy),
    };
  }

  /**
   * Parses persisted strategy value into enum when valid.
   */
  parseStrategy(value: string | null): MatchStrategy | null {
    if (!value) {
      return null;
    }

    return ALL_STRATEGIES.includes(value as MatchStrategy) ? (value as MatchStrategy) : null;
  }

  /**
   * Parses persisted formation value into enum when valid.
   */
  parseFormation(value: string | null): MatchFormation | null {
    if (!value) {
      return null;
    }

    return ALL_FORMATIONS.includes(value as MatchFormation) ? (value as MatchFormation) : null;
  }

  /**
   * Strategy-based possession influence.
   */
  resolvePossessionStrategyBonus(strategy: MatchStrategy | null): number {
    switch (strategy) {
      case MatchStrategy.POSSESSION:
        return 0.08;
      case MatchStrategy.BALANCED:
        return 0.03;
      case MatchStrategy.ATTACK:
        return 0.02;
      case MatchStrategy.COUNTER_ATTACK:
        return -0.03;
      case MatchStrategy.DEFENSE:
        return -0.04;
      default:
        return 0;
    }
  }

  /**
   * Estimates midfield structure value from formation shape.
   */
  estimateFormationMidfieldWeight(formation: MatchFormation | null): number {
    if (!formation) {
      return 0;
    }

    const blocks = formation
      .split('-')
      .map((value) => Number(value))
      .filter((value) => Number.isFinite(value));

    if (blocks.length < 3) {
      return 0;
    }

    const midfieldBlocks = blocks.slice(1, blocks.length - 1);
    return midfieldBlocks.reduce((sum, block) => sum + block, 0) - 3;
  }

  /**
   * Returns tactical compatibility penalty in points.
   */
  private resolveCompatibilityPenaltyPoints(
    strategy: MatchStrategy | null,
    formation: MatchFormation | null,
  ): number {
    if (!strategy || !formation) {
      return 0;
    }

    const compatibleFormations = STRATEGY_COMPATIBILITY[strategy] || [];
    return compatibleFormations.includes(formation) ? 0 : 10;
  }

  /**
   * Returns line boosts (attack/defense/midfield) generated by strategy.
   */
  private resolveLineBoost(strategy: MatchStrategy | null): TacticalLineBoost {
    switch (strategy) {
      case MatchStrategy.ATTACK:
        return { attack: 8, defense: -4, midfield: 0 };
      case MatchStrategy.DEFENSE:
        return { attack: -6, defense: 8, midfield: 2 };
      case MatchStrategy.PENALTIES:
        return { attack: -2, defense: 2, midfield: 1 };
      case MatchStrategy.COUNTER_ATTACK:
        return { attack: 4, defense: 3, midfield: 1 };
      case MatchStrategy.BALANCED:
        return { attack: 2, defense: 2, midfield: 2 };
      case MatchStrategy.POSSESSION:
        return { attack: 2, defense: 1, midfield: 7 };
      default:
        return { attack: 0, defense: 0, midfield: 0 };
    }
  }

  /**
   * Returns strategy line impact (attack/defense/midfield) for catalog responses.
   */
  public getStrategyLineImpact(strategy: MatchStrategy): TacticalLineBoost {
    return this.resolveLineBoost(strategy);
  }
}
