export enum WorldCupStage {
  GROUP_STAGE = 'GROUP_STAGE',
  ROUND_OF_32 = 'ROUND_OF_32',
  ROUND_OF_16 = 'ROUND_OF_16',
  QUARTER_FINALS = 'QUARTER_FINALS',
  SEMI_FINALS = 'SEMI_FINALS',
  THIRD_PLACE = 'THIRD_PLACE',
  FINAL = 'FINAL',
}
